### ISSUE TITLE
TypeError: Cannot read properties of `undefined` (reading `key`)

### ISSUE THREAD

**Issue by Dhaval8087** [Qytera-Gmbh/cypress-xray-plugin#119]
cypress-xray-plugin version - 3.3.3
cypress version -  12.16.0
I am trying to upload the e2e test execution into Xary server, I am getting error like 

` Cypress Xray Plugin | ERROR   | Failed to upload results to Xray: "TypeError: Cannot read properties of undefined (reading 'key')"`

Please find the cypress config 

```ts
// @ts-ignore
import {defineConfig} from "cypress"
import { addXrayResultUpload, configureXrayPlugin } from "cypress-xray-plugin/plugin"


export default defineConfig({
  reporter: 'junit',
  video:false,
  reporterOptions: {
    mochaFile: 'cypress/results/output.xml',
  },
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    async setupNodeEvents(on, config) {
        // implement node event listeners here
        await configureXrayPlugin({
          plugin: {
            debug: true,
            overwriteIssueSummary: true
          },
          jira: {
              projectKey: "projectkey",
              url:"jiraurl"
          },
          xray: {
            statusPassed: "SUCCESS",
            uploadResults: true
         },
      });
      await addXrayResultUpload(on);
    },
    baseUrl: 'base url',
  },
})
```
my test.cy.ts file looks like 
```ts

//@ts-nocheck

describe('The UserName/Password Field', () => {
    beforeEach(()=>{
        cy.visit('/')
    });
    it("Load the Kuma Title", () => {
      cy.get('input[name="username"]').type('username');
      cy.wait(500);
      cy.get('[data-cy="login"]').should('exist').click();
      cy.wait(4000);
      cy.get('[data-cy="kuma"]').should('exist').click();
      cy.wait(2000);
    });
});
```

in Gitlab CI it's throwing the type error **"Failed to upload results to Xray: "TypeError: Cannot read properties of undefined (reading 'key')"** 

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/7660739/cc0142df-d5d4-43b0-ad03-950761cc1dd5)

**Comment by csvtuda** [comment]
Hey @Dhaval8087,

thank you for raising the issue. I see that you have debug logging enabled and your screenshot tells me that the results import request went through just fine.

Can you check what the `data` property contains in file `GET_https_[...]_import_execution_1690047539266_response.json`? It should _usually_ contain something like:
```ts
data: {
  testExecIssue: {
    key: "PROJECT-12345"
  }
}
```

If you've deleted it, please repeat the scenario and check the contents of the response just before the error occurs.

**Comment by Dhaval8087** [comment]
@csvtuda Hey Sorry for the late reply , I have attached a log file of
GET_https_jira_rest_raven_latest_api_import_execution_1690178879367_response.json file 

[logs.txt](https://github.com/Qytera-Gmbh/cypress-xray-plugin/files/12159802/logs.txt)

**Comment by csvtuda** [comment]
Thank you for the logs. The response contains a login page as content. I don't really understand, from the information you've provided everything seems fine:
- you're using Xray server
- according to [this](https://docs.getxray.app/display/XRAY/Import+Execution+Results+-+REST#ImportExecutionResultsREST-XrayJSONresults) the import execution URL is correct for Xray server: `[...]/rest/raven/latest/api/import/execution`

The only curious thing is that the response debug message is a `GET` response, although a `POST` was sent.

When I try to access one of the publicly available API endpoints of your Jira instance (which can be accessed anonymously/without credentials):
```sh
curl https://skyway.porsche.com/jira/rest/api/2/dashboard
```
it redirects me:
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
   <head>
      <title>302 Found</title>
   </head>
   <body>
      <h1>Found</h1>
      <p>The document has moved <a href="https://skyway.porsche.com/crowd/plugins/servlet/saml-login?redirect=%2fjira%2frest%2fapi%2f2%2fdashboard">here</a>.</p>
   </body>
</html>
```

Ideally, the response should look something like this:

```json
{
   "startAt":0,
   "maxResults":20,
   "total":1,
   "dashboards":[
      {
         "id":"10000",
         "name":"System Dashboard",
         "self":"https://skyway.porsche.com/jira/rest/api/2/dashboard/10000",
      }
   ]
}
```

Can you make sure to use the actual Jira URL instead of the one which leads to redirects?
