### ISSUE TITLE
Summary of corresponding issue is missing

### ISSUE THREAD

**Issue by csvtuda** [Qytera-Gmbh/cypress-xray-plugin#156]
> I was using the `3.3.3` version and the results were being upload without problems, but in the new version I'm facing upload skips. Do you know anything about it?

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/57810270/f1dd8550-c87a-43e5-909e-d65b7e3dadfc)

_Originally posted by @RenanPaixao in https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/152#issuecomment-1691744749_

**Comment by csvtuda** [comment]
Hey @RenanPaixao,

Versions `4.0.0` started treating issues as the single source of truth, meaning that the plugin is not allowed to change summaries anymore (without explicit permission, that is). To prevent that from happening, it needs to fetch all issue summaries from Jira before uploading results.

Your error means that the plugin failed to fetch the summary of `SMA-4349`. Can you set the plugin to [debug mode in the options](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/plugin/#debug):

```ts
plugin: {
  debug: true
}
```

and run the tests again? The plugin should create at least one file called something like:

```sh
<timestamp>_POST_https_<domain>.atlassian.net_rest_api_3_search_response.json
```

Inside this file, you should be able to find data like this:

```json
"data": {
  "expand": "schema,names",
  "startAt": 0,
  "maxResults": 50,
  "total": 3,
  "issues": [
    {
      "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
      "id": "12662",
      "self": "https://<domain>.atlassian.net/rest/api/3/issue/12662",
      "key": "CYP-412",
      "fields": { "summary": "Fails a test" }
    },
    {
      "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
      "id": "12661",
      "self": "https://<domain>.atlassian.net/rest/api/3/issue/12661",
      "key": "CYP-411",
      "fields": { "summary": "Contains a link" }
    },
    {
      "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
      "id": "12660",
      "self": "https://<domain>.atlassian.net/rest/api/3/issue/12660",
      "key": "CYP-410",
      "fields": { "summary": "Contains a title" }
    }
  ]
},
```

Can you confirm that there is such a file and that it contains data like this, especially for `SMA-4349`?

**Comment by caique-raidiam** [comment]
@RenanPaixao this could be because your jira is in Portuguese, change to English in the Hira Settings interface and try again, this fixed the same issue for me

**Comment by RenanPaixao** [comment]
@caique-raidiam @csvtuda I found the problem. I was missing `JIRA_USERNAME` variable and getting a 403 error.

Apparently the `API_TOKEN` is enough to connect with the version 2 jira api, what is used by the version `3.3.3` plugin, but the newest plugin version connect with the jira api in version 3, that requires the `JIRA_USERNAME`

**Comment by csvtuda** [comment]
Happy to hear it's working now. Out of curiosity, are you using a Jira/Xray server setup or Jira/Xray cloud?

**Comment by RenanPaixao** [comment]
I'm using Jira/Xray cloud setup

**Comment by csvtuda** [comment]
Interesting, I will look into it and maybe adapt the documentation accordingly 🤔 Thanks!
