### ISSUE TITLE
Add option to choose Jira API version

### ISSUE THREAD

**Issue by RenanPaixao** [Qytera-Gmbh/cypress-xray-plugin#163]
Would be interesting to have a key in plugin configuration object to choose the jira api version?

something like 
```
plugin: {
  jiraApiVersion: 2,
  debug: true
}
```

For some reason the plugin is working locally, but isn't in CI, only the `3.3.3` plugin version, that apparently uses the version 2 JIRA API.

I have set up all credentials needed.
![screen-plugin](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/57810270/756f57a2-098a-4efd-98d7-2d0c49daf73d)

But even so I got the summary error:
![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/57810270/704bcfbe-b4b8-4a09-9bf1-52de01b76da4)

**Comment by csvtuda** [comment]
Hey, thanks for the suggestion. 

I'm not entirely opposed to it, but I'd like to investigate your problem a little more (Jira explicitly states that the APIs offer the same functionalities).

- Do you have any additional plugins/cypress modifications going on?
- Are the credentials you're using in CI different from your local ones?

What would help me most is if you shared the `data` as described [here](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/156#issuecomment-1691846079) (_only_ the data, not the headers containing your credentials). You can obviously replace the summaries and domain with garbage text, if you don't want to share them.

**Comment by RenanPaixao** [comment]
It's probably a difference in CI environment and my machine that I can't identify

1. We have 2 plugins being used. 1 for coverage and other is the `dotenv`, which I had checked and was working fine locally.
2. The credentials are the same. I ran and checked several times.

I will try to get the data that you needs and put it here when possible

**Comment by RenanPaixao** [comment]
@csvtuda only updating, I got vacations a while ago and when I go back to work, I will try to get the logs on CI enviroment as you suggested

**Comment by RenanPaixao** [comment]
@csvtuda I just ran some tests with the version 4.0.4 and it mysteriously worked. Before, the problem happens in 4.0.2. (I cannot use versions 5> because the node version cap)

Thanks!

**Comment by csvtuda** [comment]
@RenanPaixao thanks for the feedback. Glad to hear it's "just working" now.

Should the issue reappear in the future feel free to reopen this issue or just create a new one. And don't forget to update Node sooner or later 😃
