### ISSUE TITLE
Test steps being deleted although `XRAY_STEPS_UPDATE` is `false`

### ISSUE THREAD

**Issue by reify-emmanuel-malave** [Qytera-Gmbh/cypress-xray-plugin#164]
Test step information is being deleted from Jira Test issues even though the environment variable XRAY_STEPS_UPDATE is set to false. I'm using cypress 12.14.0 and cypress-xray-plugin 4.0.3. Is there a way we can keep the manually written test steps without updating or deleting them when we send in a new test execution from the plugin?

**Comment by csvtuda** [comment]
Hey @reify-emmanuel-malave,

thanks for raising this issue, I can reproduce it and will release a fix!

**Comment by csvtuda** [comment]
The issue should be fixed in version `4.0.4`.

**Comment by reify-emmanuel-malave** [comment]
It's working as expected now. Thank you for the fast fix!
