### ISSUE TITLE
Jira description and summary modified when nothing but `testExecutionIssueKey` is set

### ISSUE THREAD

**Issue by marvinpivaralreveal** [Qytera-Gmbh/cypress-xray-plugin#191]
According to the documentation https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#testexecutionissuedescription if I add the Test Execution Issue Key and omit adding a description or summary the plugin will not modify the existing description and summary, it is understood that the ones it already contains will remain before loading the results, but after running my tests the plugin adds the default values to each one.

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/130388041/f9a6aa6d-365a-41d1-a855-8d8f534e712a)

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/130388041/57ce110f-1b0d-41a5-af18-386ce8e2b99a)

**Comment by marvinpivaralreveal** [comment]
By the way, excellent plugin developed, it has a lot of potential to help with loading executions with Xray.

**Comment by csvtuda** [comment]
Hey @marvinpivaralreveal,

thanks for raising this issue. You're right, the code does not match the documentation. I guess the behaviour as stated in the documentation is the more intuitive one, so I will try to adapt the code accordingly.

**Comment by marvinpivaralreveal** [comment]
Excellent, really having the option of being able to upload the results to a test execution without modifying it is a good option, since many times test executions are created manually from Jira and only the tests to be executed are assigned to it, I look forward to seeing it working the correction :D greetings.

**Comment by csvtuda** [comment]
I just released version 5.1.0, which includes a fix for your issue. Please let me know if this version stops existing summaries and descriptions from being overwritten when not specifying them explicitly.

**Comment by marvinpivaralreveal** [comment]
I update to the new version and try again, it works excellent when I omit the description and summary as input variables. thank you so much.

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/130388041/8928de07-c3ad-4fc0-914c-78163277e4c8)

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/130388041/082e3da1-7c29-44fc-bc2b-be4f6fc9fc2d)
