### ISSUE TITLE
Manual test steps are cleared on results upload

### ISSUE THREAD

**Issue by ztarsoly** [Qytera-Gmbh/cypress-xray-plugin#209]
Hello!

I use your Xray plugin to upload test results. I targeted existing manual tests, but unfortunately after the result import the test steps has been disappeared from the tests. Also, if I target generic tests, the test definition is cleared as well. Could you please tell me what can be the problem? Thanks in advance!

Version: 5.1.0

Best regards,
Zoltan Tarsoly

**Comment by csvtuda** [comment]
Hey @ztarsoly,

so if I understand correctly, the situation of your first problem is as follows:
1. you have existing manual tests with test steps defined
2. you upload test results using this plugin
3. the test steps disappear

This should not happen, the plugin is not allowed to change/delete test steps of existing tests. Would you mind sharing your plugin configuration? Feel free to obfuscate any sensitive data (Jira URLs, ...).

---

Regarding the generic test definition, let's move the discussion here: https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/210

**Comment by ztarsoly** [comment]
Hello Basti,

you described my situation correctly.

Here is my plugin config:
`await configureXrayPlugin(config, {
        plugin: {
          enabled: false
        },
        jira: {
          projectKey: "***",
          url: "https://***.atlassian.net",
          testExecutionIssueSummary: "***"
        }
      });`
I turn on your plugin with env variable on the CI.

**Comment by csvtuda** [comment]
Hey @ztarsoly,

Updating to version [`5.1.1`](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#511) should fix for the issue. Please let me know if that's the case.

**Comment by ztarsoly** [comment]
Hello @csvtuda ,

with version 5.1.1 everything seems good to me. Test steps are not changed after importing results. Ty for your quick fix!
