### ISSUE TITLE
Generic test definitions are removed on results upload

### ISSUE THREAD

**Issue by csvtuda** [Qytera-Gmbh/cypress-xray-plugin#210]
> Also, if I target generic tests, the test definition is cleared as well. Could you please tell me what can be the problem?

_Originally posted by @ztarsoly in https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/209_

---            

I can reproduce the problem and have identified the bug/missing piece. 

However, I have never worked with generic tests, so I could use some input on how to approach this @ztarsoly.

Would you like to be able to:
1. keep existing test definitions?
2. change test definitions through the plugin?

I don't really know what to do with them.

**Comment by ztarsoly** [comment]
Hello Basti,

it should keep the existing test definition.

**Comment by csvtuda** [comment]
Hey @ztarsoly,

I just released version [`5.1.1`](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#511), which should include a fix for your issue. Please let me know if that's the case.

**Comment by ztarsoly** [comment]
Hello @csvtuda ,

with version 5.1.1 everything seems okay to me. Definition field holds its value. Thank you so much for the quick fix!
