### ISSUE TITLE
Emails from Jira say changes are done on xray ticket when they are none made

### ISSUE THREAD

**Issue by alexviz7** [Qytera-Gmbh/cypress-xray-plugin#211]
Hello, 

First of all  I want to tell you that the xray plugin configuration is up on Bamboo CI/CD running. There we have set the plugin true on Bamboo and false in the cypress configuration.
However I receive each time the test execution is running hundrets of emails that all my test tickets had changes in their titles. 
![Screenshot 2023-10-12 112510](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/6b31fcc6-e49e-4bcc-823d-323ce8403bc2)

In the logs i also see this:
```
build  10-Oct-2023 13:20:28  │ Cypress Xray Plugin │ DEBUG   │ Resetting issue summary of issue: TC-2872
build  10-Oct-2023 13:20:28  │ Cypress Xray Plugin │ DEBUG   │ ┊ 
build  10-Oct-2023 13:20:28  │ Cypress Xray Plugin │ DEBUG   │ ┊   Summary pre sync:  Test UI: Bitmasken als Projektadministrator anzeigen
build  10-Oct-2023 13:20:28  │ Cypress Xray Plugin │ DEBUG   │ ┊   Summary post sync: Bitmasken als Projektadministrator anzeigen
build  10-Oct-2023 13:20:28  │ Cypress Xray Plugin │ DEBUG   │ ┊
build  10-Oct-2023 13:20:28  │ Cypress Xray Plugin │ DEBUG   │ Editing issue...
build  10-Oct-2023 13:20:28  │ Cypress Xray Plugin │ DEBUG   │ Request:  /appl/bamboo-agent/xml-data/build-dir/TC-TCF1354-RET/frontend/trustcenter/logs/1696936828255_PUT_https_devstack.vwgroup.com_jira_rest_api_2_issue_TC_2872_request.json
build  10-Oct-2023 13:20:28  │ Cypress Xray Plugin │ DEBUG   │ Response: /appl/bamboo-agent/xml-data/build-dir/TC-TCF1354-RET/frontend/trustcenter/logs/1696936828950_PUT_https_devstack.vwgroup.com_jira_rest_api_2_issue_TC_2872_response.json
build  10-Oct-2023 13:20:28  │ Cypress Xray Plugin │ DEBUG   │ Successfully edited issue: TC-2872
```
It looks like **Test UI:** is deleted and then re edited.

**Comment by csvtuda** [comment]
Hey @alexviz7,

thanks for pointing this out. I assume you're using Cucumber and have enabled feature file synchronization, right?

Unfortunately, there's no way to prevent that right now as far as I know. When importing feature files to Xray, existing summaries/labels are thrown away and replaced with the ones from the imported file. There's no way to prevent that, that's how Xray built their API.

This leads to two outcomes:
1. Import the feature file without resetting summaries/labels back to their previous version. Prevents E-Mail flood, but changes existing data.
2. Import the feature file and reset summaries/labels afterwards. Prevents changes to existing data, but leads to E-Mail flood.

I cannot really do anything about the E-Mails. Summary resetting was a requested feature: https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/100, so I'd really like to keep it.

I hope this clears it up.

**Comment by alexviz7** [comment]
Yes  
```
await configureXrayPlugin(config, {
    jira: {
      projectKey: 'TC',
      url: 'https://devstack.com/jira',
    },
    cucumber: {
      featureFileExtension: '.feature',
      uploadFeatures: true,
    },
    xray: {
      statusPassed: 'PASS',
      statusFailed: 'FAIL',
      statusSkipped: 'ABORTED',
      uploadResults: true,
      uploadScreenshots: true,
    },
    plugin: {
      enabled: false,
    },
  });
  await addXrayResultUpload(on);
```

Well it was me who opened that issue #100 . I wanted to keep the title unchanged. The email should not be send if no changes have been done. So its a bug I guess.

**Comment by csvtuda** [comment]
I understand where you're coming from, and I absolutely get that what you're describing is a ridiculous amount of mails. 

But the point is: from Jira's point of view, there _are_ changes during each upload which it wants to report using mails:

```ts
test issue exists
         ↓
plugin uploads feature file
         ↓
test issue has updated summary // Jira sends E-Mail
         ↓
plugin resets the summary
         ↓
test issue has old summary // Jira sends E-Mail
```

The fact that Jira sends mails in this case is not this plugin's fault or bug. Xray currently does not offer any other way to keep the summaries as is other than resetting them manually again.

---

The import feature file endpoint is quite problematic, as you can see in these bugs:

- https://jira.getxray.app/browse/XRAY-9444
- https://jira.getxray.app/browse/XRAY-8664
- https://jira.getxray.app/browse/XRAYCLOUD-1716
- https://jira.getxray.app/browse/XRAY-8371
- https://jira.getxray.app/browse/XRAY-6759

There's one thing which I could still try out, but apart from that all I can do is suggest that either you or I open an issue in Xray's issue tracker.

**Comment by alexviz7** [comment]
ok i understand, i hope you find a solution otherwise I have to do 2 of the options you gave me.
However if there would be an option to for example give in the configuration a prefix of the (title) summary would this end the issue?

**Comment by csvtuda** [comment]
I tried the last thing I wanted to try (multipart feature import with additional field JSON for setting the summary), but it did not work. I've contacted Xray's support on how to proceed with this. I will link it here should they create a feature request/bug for this.

---

Regarding your suggestion: I would prefer not to add such highly specific options. However: you can already add title prefixes yourself (similar to [here](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/79#issuecomment-1696110799)):

#### 1. Create a function which parses feature files, updates scenario names and writes new feature files to some temporary location:

```ts
import { AstBuilder, GherkinClassicTokenMatcher, Parser } from "@cucumber/gherkin";
import { pretty } from "@cucumber/gherkin-utils";
import { IdGenerator } from "@cucumber/messages";
import fs from "fs";
import path from "path";

/**
 * This function does three things basically:
 * 1. Parse the feature file
 * 2. Apply scenario name logic
 * 3. Create new feature file in temporary directory
 *
 * @param featurePath - path to the original feature file
 * @param projectRoot - the Cypress project root
 * @returns the path to a feature file with updated scenario names
 */
export function prependTitleToScenarios(
  featurePath: string,
  projectRoot: string
): string {
  if (!featurePath.endsWith(".feature")) {
    return featurePath;
  }

  // 1. Parse feature file
  // See: https://github.com/cucumber/gherkin#library
  const uuidFn = IdGenerator.uuid();
  const builder = new AstBuilder(uuidFn);
  const matcher = new GherkinClassicTokenMatcher();
  const parser = new Parser(builder, matcher);
  const gherkinDocument = parser.parse(
    fs.readFileSync(featurePath, { encoding: "utf-8" })
  );

  if (!gherkinDocument.feature) {
    return featurePath;
  }

  // 2. Apply scenario name logic
  // Children can be: background, scenarios, ...
  const children = gherkinDocument.feature.children;
  for (const child of children) {
    if (child.scenario) {
      child.scenario.name = `Test UI: ${child.scenario.name}`;
    }
  }

  const root = path.join(projectRoot, "cypress", "e2e");
  const filedir = path.basename(path.dirname(featurePath));
  const filename = path.basename(featurePath);
  const tmpFilepath = path.join(root, filedir, "generated", filename);
  fs.mkdirSync(path.dirname(tmpFilepath), { recursive: true });
  fs.writeFileSync(tmpFilepath, pretty(gherkinDocument, "gherkin"));
  return tmpFilepath;
}
```

#### 2. Exclude generated feature files from test execution:

```ts
export default defineConfig({
  e2e: {
    // ....
    excludeSpecPattern: ["cypress/e2e/**/generated/**"],
  },
});
```

#### 2. Call the function during file preprocessing:

```ts
export default defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      const fixedOn = fix(on);
      await configureXrayPlugin(config, {
        // ...
      });
      await addCucumberPreprocessorPlugin(fixedOn, config);
      await addXrayResultUpload(fixedOn);
      fixedOn("file:preprocessor", async (file: Cypress.FileObject) => {
        file.filePath = prependTitleToFeature(
          file.filePath,
          config.projectRoot
        );
        await syncFeatureFile(file);
        const cucumberPlugin = createBundler({
          plugins: [createEsbuildPlugin(config)],
        });
        return cucumberPlugin(file);
      });
      return config;
    },
  },
});
```

**Comment by alexviz7** [comment]
Ok thank you very much for the detailed answer. The reason I used the prefixes from the start is Jira itself. 
When I added a new Test to a UI ticket I had the Test prefix already in the title
![Screenshot 2023-10-16 102244](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/7aef43d8-31d7-4bbc-9adb-8c280758637b)
![Screenshot 2023-10-16 102335](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/51c23667-3471-4105-960c-bb0e2ee41c0a)

I hope Xray can answer to you and give us a solution to the issue.

**Comment by alexviz7** [comment]
![Screenshot 2023-10-17 174816](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/8713fe04-d4d0-497e-9ae8-3d1188c4a872)

Here I saw another email which showed this change.

**Comment by csvtuda** [comment]
Hey @alexviz7,

Just to let you know, I received some feedback for a bug related to the feature file import: https://jira.getxray.app/browse/XRAYCLOUD-6503

However, this one is not _that_ related to your problem. For this I am still waiting for an answer.

**Comment by alexviz7** [comment]
Hi, the project is using Jira server and consequently XRay server, so I think there is not much to do. I managed to contain the issue by filtering the build address in my mailbox into a separate folder.

**Comment by csvtuda** [comment]
Okay thank you, I will keep this mitigation approach in mind when people complain about this in the future 👍
