### ISSUE TITLE
Feature request: support of Xray test environment field

### ISSUE THREAD

**Issue by ztarsoly** [Qytera-Gmbh/cypress-xray-plugin#223]
Hello @csvtuda ,

it would be great if we can add the test environment for the test execution result. It is an Xray field, not a Jira one.

Thanks in advance!

Best,
Zoltan

**Comment by csvtuda** [comment]
Hey @ztarsoly,

thanks for the suggestion, this sounds like a good addition! I will try to add it as soon as possible.

**Comment by csvtuda** [comment]
I just released version `5.2.0`, which added test environment support. You should now be able to set test environments ([documentation](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/xray/#testenvironments)) to associate with each test execution.

> **Warning**
> Please be aware that if you reuse existing test execution issues, Xray will replace all existing test environments with the ones you provide to the plugin.

**Comment by ztarsoly** [comment]
It works like a charm. Thank you for your effort!
