### ISSUE TITLE
Unable to customize Jira field values when uploading results

### ISSUE THREAD

**Issue by rosemichaele** [Qytera-Gmbh/cypress-xray-plugin#235]
Hello!

I have the plugin successfully configured and uploading results, but I am attempting to provide a custom value for the "Summary" field (for example) of my XRay test execution without success. I have tried using the command line, the `cypress.env.json` file, the `cypress.config.js` file, and setting the `env` object directly in an example as described [in the Cypress docs](https://docs.cypress.io/guides/guides/environment-variables#Single-test-configuration). I always get the same result, which is the default test execution summary "Execution results [timestamp]" with the default description containing the Cypress version and the browser version. I had the same issue when attempting to customize the description field.

**Latest example that I expect to customize the summary field**:

```javascript
it(
    "PRJ-12345 My Example Test",
    {
      tags: ["@smoke", "@slow"],
      env: {
        JIRA_FIELDS_SUMMARY: 'test summary'
      }
    },
...
}
```

**Result**:

![Screenshot 2023-10-26 at 5 02 57 PM](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/17931652/7633f907-c981-4793-9cce-a70a56f40361)

Am I correctly understanding how to use [this feature](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#summary)? Am I missing something obvious? I have confirmed in each case that the environment variable is set via `Cypress.env()`. Happy to provide any other details for troubleshooting.

```
Cypress version: 11.2.0
Plugin version: 5.2.0
Node version: 18.12.0
```

I appreciate the plugin and any assistance here.

**Comment by csvtuda** [comment]
Hey @rosemichaele,

thanks for the detailed issue report.

Luckily, I think it's just a misconfiguration. The option you're looking for is [`jira.testExecutionIssueSummary`](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#testexecutionissuesummary). You should be able to set the summary there.

---

The `jira.fields` options serve a different purpose. Users can specify Jira field IDs here, such as `customfield_12345` (pretty much every field has an interal ID in Jira). They are only accessed/required when:
- synchronizing Cucumber feature files (because the plugin needs to reset the fields after feature file import) and
- they aren't uniquely identifiable (as described [here](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#fields))

I should probably rename the `jira.fields` option to `jira.fieldIds` in the future to make the intention clearer.

---

Let me know if this helps!

**Comment by csvtuda** [comment]
Glad to hear it's working 👍 

---

I'm not sure I understand your use case. Would you like to set environment variables on a per-suite basis and create different execution issues for each suite? 

There currently is no way to "split" Cypress test results into multiple execution issues apart from running the suites separately from each other and providing different environment variables for each run. In other words, the plugin creates/uses only _one_ test execution issue containing the results of _all_ executed tests/suites.

I don't think I could implement an automated way of creating such split issues currently. There are two problems:
- Big: Cypress does not propagate environment variables set within `describe` or `it` to the events it fires and my plugin listens to.

  <details>
  <summary>Example</summary>
 
  For example, the following setup demonstrates the limited information the plugin receives from Cypress. If you inspect the JSON, you will find no mention of the environment variables.

  ```js
  // spec.cy.js
  describe('template spec', () => {
    it('passes', () => {
      cy.visit('https://example.cypress.io')
    })
  })

  describe('template spec with env', {env: {A: 4, B: 3}},  () => {
    it('passes', {env: {C: "hello"}},  () => {
      cy.visit('https://example.cypress.io')
    })
  })
  ```

  ```js
  // cypress.config.js
  const { defineConfig } = require("cypress");
  const fs = require("fs")

  module.exports = defineConfig({
    e2e: {
      setupNodeEvents(on, config) {
        on("after:run", (results) => fs.writeFileSync("resultsRun.json", JSON.stringify(results, null, 2)) )
      },
    },
  });
  ```

  <details>
  <summary>JSON</summary>

  ```json
  {
    "browserName": "electron",
    "browserPath": "",
    "browserVersion": "114.0.5735.289",
    "config": {
      "projectRoot": "/home/csvtuda/Repositories/cypress/235",
      "projectName": "235",
      "configFile": "cypress.config.js",
      "isTextTerminal": true,
      "animationDistanceThreshold": 5,
      "arch": "x64",
      "baseUrl": null,
      "blockHosts": null,
      "chromeWebSecurity": true,
      "clientCertificates": [],
      "defaultCommandTimeout": 4000,
      "downloadsFolder": "/home/csvtuda/Repositories/cypress/235/cypress/downloads",
      "env": {},
      "execTimeout": 60000,
      "experimentalCspAllowList": false,
      "experimentalFetchPolyfill": false,
      "experimentalInteractiveRunEvents": false,
      "experimentalRunAllSpecs": false,
      "experimentalMemoryManagement": false,
      "experimentalModifyObstructiveThirdPartyCode": false,
      "experimentalSkipDomainInjection": null,
      "experimentalOriginDependencies": false,
      "experimentalSourceRewriting": false,
      "experimentalSingleTabRunMode": false,
      "experimentalStudio": false,
      "experimentalWebKitSupport": false,
      "fileServerFolder": "/home/csvtuda/Repositories/cypress/235",
      "fixturesFolder": "/home/csvtuda/Repositories/cypress/235/cypress/fixtures",
      "excludeSpecPattern": "*.hot-update.js",
      "includeShadowDom": false,
      "keystrokeDelay": 0,
      "modifyObstructiveCode": true,
      "numTestsKeptInMemory": 0,
      "platform": "win32",
      "pageLoadTimeout": 60000,
      "port": 53933,
      "projectId": null,
      "redirectionLimit": 20,
      "reporter": "spec",
      "reporterOptions": null,
      "requestTimeout": 5000,
      "resolvedNodePath": "/home/csvtuda/opt/Node/20.9.0/node",
      "resolvedNodeVersion": "20.9.0",
      "responseTimeout": 30000,
      "retries": {
        "runMode": 0,
        "openMode": 0
      },
      "screenshotOnRunFailure": true,
      "screenshotsFolder": "/home/csvtuda/Repositories/cypress/235/cypress/screenshots",
      "slowTestThreshold": 10000,
      "scrollBehavior": "top",
      "supportFile": "/home/csvtuda/Repositories/cypress/235/cypress/support/e2e.js",
      "taskTimeout": 60000,
      "testIsolation": true,
      "trashAssetsBeforeRuns": true,
      "userAgent": null,
      "video": false,
      "videoCompression": false,
      "videosFolder": "/home/csvtuda/Repositories/cypress/235/cypress/videos",
      "viewportHeight": 660,
      "viewportWidth": 1000,
      "waitForAnimations": true,
      "watchForFileChanges": false,
      "specPattern": "cypress/e2e/**/*.cy.{js,jsx,ts,tsx}",
      "browsers": [
        {
          "channel": "stable",
          "displayName": "Chrome",
          "family": "chromium",
          "majorVersion": "118",
          "name": "chrome",
          "path": "/home/csvtuda/opt/Google/Chrome/Application/chrome",
          "version": "118.0.5993.118"
        },
        {
          "channel": "stable",
          "displayName": "Firefox",
          "family": "firefox",
          "majorVersion": "118",
          "name": "firefox",
          "path": "/home/csvtuda/opt/Mozilla Firefox/firefox",
          "version": "118.0.2"
        },
        {
          "channel": "stable",
          "displayName": "Edge",
          "family": "chromium",
          "majorVersion": "118",
          "name": "edge",
          "path": "/home/csvtuda/opt/Microsoft/Edge/Application/msedge.exe",
          "version": "118.0.2088.69"
        },
        {
          "channel": "stable",
          "displayName": "Electron",
          "family": "chromium",
          "majorVersion": 114,
          "name": "electron",
          "path": "",
          "version": "114.0.5735.289"
        }
      ],
      "cypressBinaryRoot": "/home/csvtuda/opt/Cypress/Cache/13.3.3/Cypress/resources/app",
      "hosts": null,
      "isInteractive": true,
      "version": "13.3.3",
      "testingType": "e2e",
      "browser": null,
      "cypressInternalEnv": "production"
    },
    "cypressVersion": "13.3.3",
    "endedTestsAt": "2023-10-27T14:53:03.274Z",
    "osName": "win32",
    "osVersion": "10.0.19045",
    "runs": [
      {
        "error": null,
        "reporter": "spec",
        "reporterStats": {
          "suites": 2,
          "tests": 2,
          "passes": 2,
          "pending": 0,
          "failures": 0,
          "start": "2023-10-27T14:53:00.854Z",
          "end": "2023-10-27T14:53:03.278Z",
          "duration": 2424
        },
        "screenshots": [],
        "spec": {
          "absolute": "/home/csvtuda/Repositories/cypress/235/cypress/e2e/spec.cy.js",
          "fileExtension": ".js",
          "fileName": "spec",
          "name": "spec.cy.js",
          "relative": "cypress/e2e/spec.cy.js"
        },
        "stats": {
          "duration": 2424,
          "endedAt": "2023-10-27T14:53:03.274Z",
          "failures": 0,
          "passes": 2,
          "pending": 0,
          "skipped": 0,
          "startedAt": "2023-10-27T14:53:00.850Z",
          "suites": 2,
          "tests": 2
        },
        "tests": [
          {
            "attempts": [
              {
                "state": "passed"
              }
            ],
            "displayError": null,
            "duration": 378,
            "state": "passed",
            "title": ["template spec", "passes"]
          },
          {
            "attempts": [
              {
                "state": "passed"
              }
            ],
            "displayError": null,
            "duration": 186,
            "state": "passed",
            "title": ["template spec with env", "passes"]
          }
        ],
        "video": null
      }
    ],
    "startedTestsAt": "2023-10-27T14:53:00.850Z",
    "totalDuration": 2424,
    "totalFailed": 0,
    "totalPassed": 2,
    "totalPending": 0,
    "totalSkipped": 0,
    "totalSuites": 2,
    "totalTests": 2
  }


  ```

  </details>
  </details>
- Small: It would be difficult to decide which environment variables to use for the final execution issue. The one in the topmost `describe`? The one in the "lowest common denominator"? Or should `it` test results be grouped into test execution issues by their environment variable values, no matter where the values were defined?

Feel free to clarify your use case a little bit more.

**Comment by rosemichaele** [comment]
I think this is related to my lack of experience with XRay, but I had assumed that each Cypress example would create a new test execution record in XRay - that's where I wanted custom details for each one. I was also running only one test while configuring the plugin. Now that I see there are multiple tests/test runs under an execution, I have a better understanding of how everything fits together.

Thanks for your help here and the quick replies!
