### ISSUE TITLE
Error: `Failed to configure Jira client: no viable authentication method was configured`

### ISSUE THREAD

**Issue by rahulworks-git** [Qytera-Gmbh/cypress-xray-plugin#244]
`Error: Failed to configure Jira client: no viable authentication method was configured`

Can someone please respond to this?

**Comment by csvtuda** [comment]
Hey @rahulworks-git,

did you set up Jira authentication as described [in the documentation](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/authentication/)?

You need to provide both Xray and Jira credentials for the plugin to work properly.

**Comment by rahulworks-git** [comment]
Yes i am using JIRA Cloud. I do have the `XRAY_CLIENT_ID`, `XRAY_CLIENT_SECRET`, `JIRA_USERNAME`, `JIRA_API_TOKEN`. I have not stored them in the code as i am passing them directly in the npx cypress run command. 

Also, i have added the following code in my cypress.config.js
`const { addXrayResultUpload, configureXrayPlugin } = require("cypress-xray-plugin");`

`e2e: {
    async setupNodeEvents(on, config) {
      await configureXrayPlugin(config, {
        jira: {
          projectKey: "KEY",
          url: "JIRA_URL_VALUE"
        },
        xray: {
          status: {
            failed: "FAILURE"
          }
        },
      });`

Please let me know if anything else is needed.

**Comment by rahulworks-git** [comment]
Also, the code i am using to run the tests is as follows:

npx cypress run --env XRAY_CLIENT_ID=VALUE, XRAY_CLIENT_SECRET=VALUE, JIRA_USERNAME=VALUE, JIRA_API_TOKEN=VALUE

**Comment by csvtuda** [comment]
Hm the combination of environment variables seems correct.

Are there spaces in between the variables here?

```console
npx cypress run --env XRAY_CLIENT_ID=VALUE, XRAY_CLIENT_SECRET=VALUE, JIRA_USERNAME=VALUE, JIRA_API_TOKEN=VALUE
```

If yes, make sure to not add any whitespace after each comma, since Cypress does not add them to the environment variables otherwise:

```console
npx cypress run --env XRAY_CLIENT_ID=VALUE,XRAY_CLIENT_SECRET=VALUE,JIRA_USERNAME=VALUE,JIRA_API_TOKEN=VALUE
```

See [here](https://docs.cypress.io/guides/guides/environment-variables#Option-4---env):
> **Warning**
> Multiple values must be separated by a comma, not a space.
