### ISSUE TITLE
Error: `Invalid time value`

### ISSUE THREAD

**Issue by leonardolnovaes** [Qytera-Gmbh/cypress-xray-plugin#255]
Hey guys.

I have a problem when I finish running my tests, it uploads it to x-ray, but it is giving an error as shown in the screenshot below

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/57955757/5ecdaddc-8e75-4c0d-a6f5-19ad500f17a6)

**Comment by csvtuda** [comment]
Hey @leonardolnovaes,

thanks for creating the issue. Would you mind sharing the following information?

- Your `cypress` version
- Your `cypress-xray-plugin` version

I have never encountered this problem. What would help the investigation immensely are your actual run results. You can obtain them like this:

```ts
// cypress.config.js
const { defineConfig } = require("cypress");
const fs = require("fs");

module.exports = defineConfig({
    e2e: {
        setupNodeEvents(on, config) {
            // other stuff
            // ...
            on("after:run", (results) =>
                // Write run results to JSON file, but skip the config containing sensitive data.
                fs.writeFileSync(
                    "resultsRun.json",
                    JSON.stringify(results, (k, v) => (k === "config" ? undefined : v), 2)
                )
            );
        },
    },
});
```

Feel free to obfuscate any test titles and file names/paths. The most important values would obviously be the time related ones.

**Comment by leonardolnovaes** [comment]
My Cypress version is 13.3.0 and my cypress-xray-plugin version is 3.3.3, this resultsRun.json is not being created when running giving the error, I can't get any other type of return to send here. I'll keep trying to debug this

**Comment by csvtuda** [comment]
Can you share your Cypress configuration file? Feel free to replace sensitive data (Jira URL, any environment variables, ...) with garbage.

**Comment by leonardolnovaes** [comment]
Thank you, it solved my problem!!
I needed to update the plugin, after that, I had to change some things but everything worked fine!
Thank you friend

**Comment by csvtuda** [comment]
Glad to hear that!
