### ISSUE TITLE
Error: `Failed to configure Xray client: Jira cloud credentials detected, but the provided Xray credentials are not Xray cloud credentials`

### ISSUE THREAD

**Issue by manoj12419** [Qytera-Gmbh/cypress-xray-plugin#265]
### Description

Command used to run:  
```sh
npx cypress run --env JIRA_USERNAME="", JIRA_API_TOKEN="",XRAY_CLIENT_ID="",XRAY_CLIENT_SECRET=""
```

jira token created based out: https://docs.searchunify.com/Content/Content-Sources/Atlassian-Jira-Confluence-Authentication-Create-API-Token.htm#:~:text=Log%20into%20Jira%20Software%20or,Click%20Create%20API%20token.

Xray credential created: https://docs.getxray.app/display/XRAYCLOUD/Global+Settings%3A+API+Keys

I am getting  this error:

```console
Error: Failed to configure Xray client: Jira cloud credentials detected, but the provided Xray credentials are not Xray cloud credentials
You can find all configurations currently supported at: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/authentication/
    at initClients (C:\Cypress_project\node_modules\cypress-xray-plugin\src\context.js:238:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async configureXrayPlugin (C:\Cypress_project\node_modules\cypress-xray-plugin\src\plugin.js:37:18)
    at async setupNodeEvents (C:\Cypress_project\cypress.config.js:7:7)
```

### Cypress version

13.6.0

### Plugin version

5.2.1

### Jira/Xray type

Cloud

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hey @manoj12419,

thanks for opening this issue. The error indicates that your environment variables did not actually reach the plugin for some reason. Can you print them out and check if Cypress actually knows about them?

```ts
// cypres.config.js

export default defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {

      console.log(config.env); // here

      await configureXrayPlugin(config, {
        jira: {
          projectKey: "CYP",
          url: "https://whatever.net",
        },
        plugin: {
          debug: false,
        },
        xray: {
          uploadResults: true,
        },
      });
    },
  },
});

```

Using your command from above, the output should look something like this:

```console
npx cypress run --env JIRA_USERNAME="",JIRA_API_TOKEN="",XRAY_CLIENT_ID="",XRAY_CLIENT_SECRET=""


DevTools listening on ws://127.0.0.1:50159/devtools/browser/d4a52df6-842f-4fe7-9c8b-cb49eaea3632
{
  JIRA_USERNAME: '',
  JIRA_API_TOKEN: '',
  XRAY_CLIENT_ID: '',
  XRAY_CLIENT_SECRET: ''
}
│ Cypress Xray Plugin │ INFO    │ Jira username and API token found. Setting up Jira cloud basic auth credentials
Your configFile threw an error from: C:\Repositories\cypress\265\cypress.config.js

The error was thrown while executing your e2e.setupNodeEvents() function:

Error: Failed to establish communication with Jira: https://whatever.net

Request failed with status code 401

Make sure you have correctly set up:
- Jira base URL: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#url
- Jira authentication: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/authentication/#jira
```

The part containing the environment variables is the important one. If one of them is missing, the plugin will throw the errors you described above.

**Comment by manoj12419** [comment]
@csvtuda  I did couple of thing to get ride of authentication issue
1. Deleted existing jira and xray authentication and added again
2. added extra space as you suggested  before JIRA_API_TOKEN  ie., npx cypress run --env JIRA_USERNAME="",JIRA_API_TOKEN="",XRAY_CLIENT_ID="",XRAY_CLIENT_SECRET=""

**Comment by csvtuda** [comment]
Can you double check that you've included the highlighted line?

```js
const { addXrayResultUpload, configureXrayPlugin } = require("cypress-xray-plugin");
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {

      console.log(config.env);

      await configureXrayPlugin(config, {
        jira: {
          projectKey: "YAK",
          url: "https://mydomain.atlassian.net",
          testPlanIssueKey: "YAK-4",
          testExecutionIssueKey: "YAK-3"
        },
        plugin: {a
          debug: false,
        },
        xray: {
          uploadResults: true,
        },
      });
      // =========================== //
      await addXrayResultUpload(on); // here
      // =========================== //
    },
    specPattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}',
    reporter: 'cypress-multi-reporters',
    reporterOptions: {
      configFile: 'reporter-config.json'
    }
  },
});
```

**Comment by manoj12419** [comment]
Oops, my mistake! I realized I had removed a crucial line, but once I added it back, everything worked fine.
In the beginning, it didn't work as expected, and while I was experimenting with the Junit report and updating it using a curl command, I accidentally removed that specific line.
You are awesome @csvtuda Thanks again. :-)
