### ISSUE TITLE
before and after hooks when plugin is disabled outputs ERROR 

### ISSUE THREAD

**Issue by delboy1978uk** [Qytera-Gmbh/cypress-xray-plugin#271]
### Description

When we run cypress locally, we do not report to JIRA, and so have the plugin disabled.
`│ Cypress Xray Plugin │ INFO    │ Plugin disabled. Skipping further configuration`
Followed by
`│ Cypress Xray Plugin │ ERROR   │ Skipping before:run hook: Plugin misconfigured: configureXrayPlugin() was not called`
If the plugin is disabled, should this not be either a WARNING or INFO ?

### Cypress version

13.1.0

### Plugin version

5.2.1

### Jira/Xray type

Cloud

### Configuration

```ts
npx cypress run --env PLUGIN_ENABLED=false
```

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hi @delboy1978uk,

thanks for opening this issue. I looked into it and it's indeed an issue with the way the plugin detects whether or not it's enabled. I will look into it!

**Comment by csvtuda** [comment]
I just released version [`5.2.2`](https://www.npmjs.com/package/cypress-xray-plugin/v/5.2.2), which should include a fix for your issue. Feel free to try it out!

**Comment by delboy1978uk** [comment]
Thank you so much for the speedy fix! It works great! And thanks for this awesome plugin!
