### ISSUE TITLE
Failed to import Cucumber execution: AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by SebastienCorrigan** [Qytera-Gmbh/cypress-xray-plugin#275]
### Description

Hello @csvtuda

I wrote this report in #151 but later saw that you have a bug reporting template.

I am having the same issue as @caique-rd, although I have a manual work around that may give a clue. In summary, I believe the issue is in the `@TestName` tag. 

Even though the docs say to use `@TestName:issuekey ` for Jira cloud instances, the upload only works when the report uses `@issuekey`. I wonder if certain versions of Jira cloud only accept `@issuekey`.

Here's the test I did:

Pre conditions:
✅ Issue PRO-100 exists in Jira (cloud instance)

1. Run a minimal cypress cucumber test

```
Feature: Minimal Feature

    @TestName:PRO-100
    Scenario: Minimal Scenario
    Given minimal Given
    When minimal When
    Then minimal Then
```
```
Given("minimal Given", () => {})
When("minimal When", () => {})
Then("minimal Then", () => {
    expect(false).to.be.true
})
```

2. The test fails with the error of this issue:  `Failed to import Cucumber execution: AxiosError: Request failed with status code 400`

```bash
│ Cypress Xray Plugin │ INFO    │ Jira username and API token found. Setting up Jira cloud basic auth credentials
│ Cypress Xray Plugin │ INFO    │ Xray client ID and client secret found. Setting up Xray cloud JWT credentials
│ Cypress Xray Plugin │ INFO    │ Authenticating to: https://xray.cloud.getxray.app/api/v2/authenticate...

│ Cypress Xray Plugin │ INFO    │ Fetching necessary Jira issue type information in preparation for Cucumber result uploads...

│ Cypress Xray Plugin │ INFO    │ Preprocessing feature file [PATH]/features/minimal.feature...

│ Cypress Xray Plugin │ INFO    │ Uploading Cucumber test results...
│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber execution: AxiosError: Request failed with status code 400
│ Cypress Xray Plugin │ WARNING │ Execution results import was skipped. Skipping remaining tasks
│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to [PATH]/logs/importExecutionCucumberMultipartError.json
```

3. Edit the cucumber-report.json, remove 'TestName:' in `tags[0].name`

before edit:
```json
        "tags": [
          {
            "name": "@TestName:PRO-100",
            "line": 3
          }
        ],
```

after edit: 

```json
        "tags": [
          {
            "name": "@PRO-100",
            "line": 3
          }
        ],
```

4. Use the Xray REST api `https://xray.cloud.getxray.app/api/v2/import/execution/cucumber` to upload the cucumber-report 

```js
    importCucumberResults(results) {
        cy.request({
            method: 'POST',
            url: 'https://xray.cloud.getxray.app/api/v2/import/execution/cucumber',
            body: results,
            headers: {
                'Authorization': `Bearer ${token}`
            }
        }).then((response) => {
            console.log(response)
        })
    }
```

5. Import is successful: a Test Execution is created

**Note**: if I remove `TestName:` from the tag in the `.feature` file, I get an error that indicates that it is required:

```bash
│ Cypress Xray Plugin │ INFO    │ Uploading Cucumber test results...
│ Cypress Xray Plugin │ WARNING │ Skipping result upload for scenario: Minimal Scenario
│ Cypress Xray Plugin │ WARNING │   
│ Cypress Xray Plugin │ WARNING │   No test issue keys found in tags of scenario: Minimal Scenario
│ Cypress Xray Plugin │ WARNING │   You can target existing test issues by adding a corresponding tag:
│ Cypress Xray Plugin │ WARNING │   
│ Cypress Xray Plugin │ WARNING │   @TestName:PRO-123
│ Cypress Xray Plugin │ WARNING │   Scenario: Minimal Scenario
│ Cypress Xray Plugin │ WARNING │     Before undefined
```

### Cypress version

13.6.0

### Plugin version

5.2.2

### Jira/Xray type

Cloud

### Configuration

```ts
const { defineConfig } = require("cypress");
const { plugins } = require('./cypress/support/plugins')
const createBundler = require("@bahmutov/cypress-esbuild-preprocessor");
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
const createEsbuildPlugin = require("@badeball/cypress-cucumber-preprocessor/esbuild");
const { addXrayResultUpload, configureXrayPlugin,  syncFeatureFile  } = require("cypress-xray-plugin");
const xraySecrets = require('./secrets/xray.json')
const fix = require('cypress-on-fix')


module.exports = defineConfig({
  projectId: "[HIDDEN]",
  env: {
    XRAY_CLIENT_SECRET: xraySecrets.client_secret,
    XRAY_CLIENT_ID: xraySecrets.client_id,
    JIRA_API_TOKEN: xraySecrets.JIRA_API_TOKEN,
    JIRA_USERNAME: xraySecrets.JIRA_USERNAME,
  },
  video: false,
  chromeWebSecurity: false,
  e2e: {
    retries: process.env.CI ? 1 : 0,
    taskTimeout: 120000,
    experimentalStudio: true,
    specPattern: "**/*.{feature,features,cy.js}",
    waitTimes: {
      debounce: 1100,
      visualCheck: 500,
      nextPage: 1000
    },
    pageLoadTimeout: 15000,
    viewportHeight: 900,
    viewportWidth: 1440,
    watchForFileChanges: false,

    async setupNodeEvents(on, config) {
      // get the environment name passed in as CLI argument:
      // --env environment=staging
      // Cypress places --env CLI args in config.env
      // get the environment file based on the environment name
      const envFile = `./cypress/config/environment.${config.env.environment}.js`
      config.environment = require(envFile).environment
      config.environment.name = config.env.environment
      config.baseUrl = config.environment.baseUrl

      console.log('Environment:', config.environment)

      // setup all of our custom plugins (gmail, readPDF, etc)
      // these plugins expose certain functions that run in Node
      // as opposed to in the Cypress navigator.
      on('task', plugins)

      const fixedOn = fix(on)
      // setup xray
      await configureXrayPlugin(
          config, 
          {
            jira: {
              projectKey: "PRO",
              url: "[HIDDEN]"
            },
            xray: {
              uploadResults: true,
            },
            cucumber: {
              featureFileExtension: ".feature"
            },
        }
      );
      // setup cucumber
      // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
      await preprocessor.addCucumberPreprocessorPlugin(fixedOn, config);
      await addXrayResultUpload(fixedOn);

      // ensure that the logs are printed to the terminal
      require('cypress-terminal-report/src/installLogsPrinter')(on,
        {
          printLogsToConsole: "always"
        });

      fixedOn("file:preprocessor", async (file) => {
        await syncFeatureFile(file);
        const cucumberPlugin = createBundler({
          plugins: [createEsbuildPlugin.createEsbuildPlugin(config)],
        });
        return cucumberPlugin(file);
      });

      return config
    }
  },
});
```

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hey @SebastienCorrigan,

thanks for opening this issue, I will look into it. How did you find out that `@issuekey` seems to be a valid alternative? I have never seen it in Xray's documentation as far as I can remember.

**Comment by csvtuda** [comment]
Your clue was extremely helpful 🥇

I mistakenly assumed that Xray Cloud _always_ requires the `TestName` prefix inside the tags. I assumed it because Xray automatically added them when exporting Cucumber test issues to feature files. Also because "it worked on my machine".

---

# Problem 

It turns out there's a setting in the Xray configuration which controls the prefix behaviour:

_Jira Settings_ > _Apps_ > _Xray_ > _Cucumber_

![grafik](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/14a25be5-3097-4b9e-9472-515a7ca87af4)

These export prefixes seem to control not only the export behaviour, but also the import behaviour, as demonstrated in the following.

When configured like in the screenshot above, I can import the following Cucumber report just fine:

```ts
// POST https://xray.cloud.getxray.app/api/v2/import/execution/cucumber
[
  {
    "elements": [
      {
        "keyword": "Scenario",
        "steps": [],
        "tags": [
          {
            "name": "@TestName:CYP-531"
          }
        ]
      }
    ]
  }
]
```
However, the following does not work:

```ts
// POST https://xray.cloud.getxray.app/api/v2/import/execution/cucumber
[
  {
    "elements": [
      {
        "keyword": "Scenario",
        "steps": [],
        "tags": [
          {
            "name": "@ThisIsATest:CYP-531"
          }
        ]
      }
    ]
  }
]
```



But if I now change the setting to this, the first import won't work anymore, whereas the second one will suddenly work:

![grafik](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/c30a1160-6e75-40fe-85fb-d7477ff90386)

# Solution

I will probably need to add prefix configurability to the plugin. Alternatively, removing it entirely like you did seems to work, too.

But before I start implementing this, would you mind confirming for me that your Cucumber export settings do _not_ contain `TestName:` in the `Test` option (otherwise you should have been able to import using `@TestName`)?

**Comment by SebastienCorrigan** [comment]
Hi @csvtuda ,

Confirmed! I haven't been able to access the app settings but I exported a Cucumber test issue. The issue tag that is present in the feature file is `@TEST_PRO-100`, hence the conflict. 

To make sure, I edited the `cucumber-report.json` again, this time with the tag: `@TEST_PRO-100`, and the import was successful 👍 . 

In conclusion, two types of tags are able to target the PRO-100 issue: `@TEST_PRO-100` (the tag configured in Jira) and simply `@PRO-100`. 'On my machine' at least.

Thanks for your help on this 🙏 , I'll probably just request a change to the Jira settings for now, and yes this could be a good configurability feature for this plugin.

**Comment by csvtuda** [comment]
Hey @SebastienCorrigan,

I just release version [`6.0.0`](https://www.npmjs.com/package/cypress-xray-plugin/v/6.0.0). The breaking changes have been documented [here](https://www.npmjs.com/package/cypress-xray-plugin/v/6.0.0).

You should be able to solve your issue by configuring the custom prefixes:

```ts
async setupNodeEvents(on, config) {
  await configureXrayPlugin(
    config,
    {
      cucumber: {
        prefixes: {
          precondition: "PRECONDITION_", // or what's configured in you Xray instance
          test: "TEST_"
        }
      }
    }
  );
}
```

Feel free to try it out and report back your findings.
