### ISSUE TITLE
Multiple reporters

### ISSUE THREAD

**Issue by hugo-gc** [Qytera-Gmbh/cypress-xray-plugin#280]
Is it possible to use this plugin along with any other reporter using cypress-multi-reporters? If so, could you provide an example for the set up? In my case, I need to generate a mochawesome html report.

**Comment by csvtuda** [comment]
Hey @hugo-gc,

yes, this is possible. All you need to do is to install the [`cypress-on-fix`](https://www.npmjs.com/package/cypress-on-fix) package:

```sh
npm i --save-dev cypress-on-fix
```

> [!IMPORTANT]
> Why `cypress-on-fix`? Because if you're using multiple plugins/registering multiple event handlers under Cypress's `on()` function, the last one to register always overwrites the previously registered ones (see https://github.com/cypress-io/cypress/issues/22428). In this case, both the `cypress-xray-plugin` and the `cypress-mochawesome-reporter` register themselves for `'after:run'` and so on. This neat little package solves the issue and allows attaching multiple hooks to the same events.

---

Here is what a somewhat minimal configuration could look like:

`cypress.config.ts`:
```ts
import { defineConfig } from "cypress";
import fix from "cypress-on-fix";
import { addXrayResultUpload, configureXrayPlugin } from "cypress-xray-plugin";

export default defineConfig({
  reporter: "cypress-mochawesome-reporter",
  e2e: {
    async setupNodeEvents(on, config) {
      const fixedOn = fix(on);
      // https://www.npmjs.com/package/cypress-mochawesome-reporter
      require("cypress-mochawesome-reporter/plugin")(fixedOn);
      // https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/setup/installation
      await configureXrayPlugin(config, {
        jira: {
          projectKey: "CYP",
          url: "https://myorg.atlassian.net",
          testExecutionIssueSummary: `Execution ${new Date().toLocaleString()}`,
        },
        xray: {
          uploadResults: true,
        },
      });
      await addXrayResultUpload(fixedOn);
    },
  },
});
```

`cypress/support/e2e.js` (see [here](https://www.npmjs.com/package/cypress-mochawesome-reporter))
```ts
import "cypress-mochawesome-reporter/register";
import "./commands";
```

`cypress/e2e/spec.cy.ts`
```ts
describe("template spec", () => {
  // https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/guides/targetingExistingIssues/
  it("CYP-529 passes", () => {
    cy.visit("https://example.org");
  });
});
```

When I run this project using my [authentication data](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/authentication/):

```sh
CYPRESS_JIRA_USERNAME=abc@def.com \
CYPRESS_JIRA_API_TOKEN=secret123 \
CYPRESS_XRAY_CLIENT_ID=id \
CYPRESS_XRAY_CLIENT_SECRET=secret456
npx cypress run
```

I get a beautiful report in `cypress/e2e/reports/html`:

![grafik](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/240236ea-3fc9-4344-aab4-f9aeb3980f88)

as well as a an execution issue in Jira:

![grafik](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/fc10832f-0073-41bc-8808-ffe9ffb8aa0c)

---

I hope this is what you were looking for.

**Comment by hugo-gc** [comment]
Hi @csvtuda 
That's exactly what I needed, it works just fine.

Thanks!
