### ISSUE TITLE
Error: Failed to configure Jira client: no viable authentication method was configured

### ISSUE THREAD

**Issue by keulenIT** [Qytera-Gmbh/cypress-xray-plugin#289]
### Description

I have set up the jira server authentication method for the xray plugin, and tested my PAT using postman. However, the authentication is still not succeeding

### Cypress version

13.6.2

### Plugin version

6.0.0

### Jira/Xray type

Server

### Configuration

```ts
run: pnpm nx e2e app-e2e --skip-nx-cache --prod JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }} JIRA_TEST_EXECUTION_ISSUE_KEY=${{ inputs.testKey }} -- --baseUrl=https://app-${{ inputs.env || 'dev' }}.domain.com --record --parallel --key=${{ secrets.CYPRESS_DASHBOARDS_KEY }} --ci-build-id=${{ github.run_id }} --tag "${{ inputs.ENV }}, ${{ github.run_id}}"

await configureXrayPlugin(config, {
    jira: {
      projectKey: 'PREZ',
      url: 'https://jira.me.com',
      attachVideos: false,
    },
    xray: {
      uploadScreenshots: true,
    },
    cucumber: {
      featureFileExtension: '.feature',
      downloadFeatures: false,
      uploadFeatures: true,
    },
  });
```

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by keulenIT** [comment]
Ah my bad... indeed I was already inputing the env config externally, so I just had to add them to the list..


`Cypress Xray Plugin │ ERROR   │   You can target existing precondition issues by adding a corresponding comment:
│ Cypress Xray Plugin │ ERROR   │   
│ Cypress Xray Plugin │ ERROR   │     Background:
│ Cypress Xray Plugin │ ERROR   │       #@GEDS-123
│ Cypress Xray Plugin │ ERROR   │       Given a base contract configuration
│ Cypress Xray Plugin │ ERROR   │       ...
│ Cypress Xray Plugin │ ERROR   │   
│ Cypress Xray Plugin │ ERROR   │   You can also specify a prefix to match the tagging scheme configured in your Xray instance:
│ Cypress Xray Plugin │ ERROR   │   
│ Cypress Xray Plugin │ ERROR   │     Plugin configuration:
│ Cypress Xray Plugin │ ERROR   │   
│ Cypress Xray Plugin │ ERROR   │       {
│ Cypress Xray Plugin │ ERROR   │         cucumber: {
│ Cypress Xray Plugin │ ERROR   │           prefixes: {
│ Cypress Xray Plugin │ ERROR   │             precondition: "Precondition:"
│ Cypress Xray Plugin │ ERROR   │           }
│ Cypress Xray Plugin │ ERROR   │         }
│ Cypress Xray Plugin │ ERROR   │       }
│ Cypress Xray Plugin │ ERROR   │   
│ Cypress Xray Plugin │ ERROR   │     Feature file:
│ Cypress Xray Plugin │ ERROR   │   
`

I'm now getting this error 

And 
`Error: Unexpected state in beforeSpecHandler: uninitialized. This almost always means that you or some other plugin, are overwriting this plugin's event handlers. For more information & workarounds, see https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/event-handlers.md (if neither workaround work, please report at https://github.com/badeball/cypress-cucumber-preprocessor)`

I'm guessing this is because I did not define a prefix config, and I will have to create a few hundred jira test issues so that I can correctly tag my tests right? From what I see in the documentation, it will not automatically create background issues.

**Comment by csvtuda** [comment]
Yes, the plugin refuses to create new Jira issues apart from test execution issues for maintainability reasons and because in the past, there was _a lot_ of confusion. So you will unfortunately need to add the comments containing precondition tags to your backgrounds.

Whether an additional prefix configuration will become necessary I cannot really tell you, it depends on your configuration.

---

> Error: Unexpected state in beforeSpecHandler: uninitialized. This almost always means that you or some other plugin, are overwriting this plugin's event handlers. For more information & workarounds, see https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/event-handlers.md (if neither workaround work, please report at https://github.com/badeball/cypress-cucumber-preprocessor)

I haven't encountered such an issue yet. Are you using the `cypress-on-fix` package as described [here](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/setup/installation/#cucumber-tests)?

```ts
import fix from "cypress-on-fix";

// [...]
// It's very important to use the fixed version
const fixedOn = fix(on);
// [...]
await addCucumberPreprocessorPlugin(fixedOn, config);
await addXrayResultUpload(fixedOn);
```

**Comment by csvtuda** [comment]
Hm interesting, would you mind sharing your cleaned up/minimal `cypress.config.ts` file (make sure to replace sensitive data with garbage)?

This would help me trace the issue further.

**Comment by keulenIT** [comment]
Sure;
`import fs from 'fs';
import path from 'path';

import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor';
import { createEsbuildPlugin } from '@badeball/cypress-cucumber-preprocessor/esbuild';
import createBundler from '@bahmutov/cypress-esbuild-preprocessor';
import fix from 'cypress-on-fix';
import { addXrayResultUpload, configureXrayPlugin, syncFeatureFile } from 'cypress-xray-plugin';
import deepmerge from 'deepmerge';

import { baseConfig } from '../config/cypress';

const projectIds: Record<string, string> = { '1251241': 'app-name-gherkin-e2e', '125121': 'app-name-gherkin-e2e' }; // eslint-disable-line @typescript-eslint/naming-convention

export type CypressOptions = Cypress.PluginConfigOptions & Partial<Omit<Cypress.RuntimeConfigOptions, 'configFile'>> & { projectId: string };

export async function sharedPlugins(on: Cypress.PluginEvents, config: Cypress.PluginConfigOptions): Promise<Cypress.PluginConfigOptions> {
  const projectId = projectIds[config.projectId ?? ''];``
  const fixedOn = fix(on);
  console.log(config.env);
  await configureXrayPlugin(config, {
    jira: {
      projectKey: 'FIRZ',
      url: 'https://jira.app.com',
      attachVideos: false,
    },
    xray: {
      uploadScreenshots: true,
    },
    cucumber: {
      featureFileExtension: '.feature',
      downloadFeatures: false,
      uploadFeatures: true,
    },
  });

  await addCucumberPreprocessorPlugin(on, config);
  await addXrayResultUpload(fixedOn);

  const mergedConfig = (
    config.configFile
      ? deepmerge(config, baseConfig(projectId ?? ''), require(config.configFile)) // dynamic import causes cypress crash (after long debugging) :(
      : deepmerge(config, baseConfig(projectId ?? ''))
  ) as CypressOptions;

  fixedOn('file:preprocessor', async file => {
    await syncFeatureFile(file);
    const cucumberPlugin = createBundler({
      plugins: [createEsbuildPlugin(mergedConfig)],
    });

    return cucumberPlugin(file);
  });

  on('before:browser:launch', (browser, options) => {
    const downloadDirectory = mergedConfig.downloadsFolder;

    if (browser.family === 'chromium') {
      if (options.preferences.default) {
        options.preferences.default['download'] = {
          // eslint-disable-next-line @typescript-eslint/naming-convention
          default_directory: downloadDirectory,
        };
      }

      return options;
    }
    if (browser.family === 'firefox') {
      options.preferences['browser.download.dir'] = downloadDirectory;
      options.preferences['browser.download.folderList'] = 2;
      options.preferences['browser.helperApps.neverAsk.saveToDisk'] = 'text/csv';

      return options;
    }

    console.table(options);

    return options;
  });

  on('task', {
    pathsExists: (paths: string[]): Promise<boolean> => hasPaths(mergedConfig, paths),
    fileExists: (fileName: string, timeout = 4000): Promise<boolean> => hasFile(mergedConfig, fileName, timeout),
    copyFixture: (obj: { source: string; target: string }, timeout = 4000): Promise<boolean> => copyFixture(mergedConfig, obj, timeout),
  });

  console.log(`clearing downloads folder: ${mergedConfig.downloadsFolder}`);
  fs.rmSync(mergedConfig.downloadsFolder, { force: true, recursive: true });

  return mergedConfig;
}

function hasPaths(config: CypressOptions, paths: string[]): Promise<boolean> {
  return hasFile(config, path.join(...paths), 4000);
}

function hasFile(config: CypressOptions, fileName: string, timeout: number): Promise<boolean> {
  const delay = 10;

  return new Promise((resolve, reject) => {
    if (timeout < 0) {
      return reject(new Error(`Could not find file ${config.downloadsFolder}/${fileName}`));
    }
    const found = fs.existsSync(`${config.downloadsFolder}/${fileName}`);
    if (found) {
      return resolve(true);
    }
    setTimeout(() => hasFile(config, fileName, timeout - delay).then(resolve, reject), 10);
  });
}

function copyFixture(config: CypressOptions, obj: { source: string; target: string }, timeout: number): Promise<boolean> {
  const fixturesDirectory = config.fixturesFolder || '';

  return new Promise((resolve, reject) => {
    if (timeout < 0) {
      return reject(new Error(`Could not copy file ${obj.source}`));
    }
    fs.copyFileSync(path.join(fixturesDirectory, obj.source), path.join(fixturesDirectory, obj.target));

    return resolve(true);
  });
}
`

**Comment by csvtuda** [comment]
From a quick glance, I think you forgot to pass the fixed `on` to the Cucumber preprocessor as well:

```diff
-  await addCucumberPreprocessorPlugin(on, config);
+  await addCucumberPreprocessorPlugin(fixedOn, config);
   await addXrayResultUpload(fixedOn);
```

Can you check if this solves your issue?

**Comment by keulenIT** [comment]
Indeed that works and I should've spotted this, thank you I'll close this now.
