### ISSUE TITLE
 Issues contained in feature file tags which were not updated by Jira and might not exist

### ISSUE THREAD

**Issue by keulenIT** [Qytera-Gmbh/cypress-xray-plugin#295]
### Description

I am encountering issues where the plugin seemingly does not seem able to link the jira issue for some tests. I write some, because for others it works fine. What I've done so far:

- Verify the issue id's actually exist inside Jira 
- Of the above verified issue id's, verify my Test type issue in Jira is actually of type Cucumber
- Not use prefixes
- Add prefixes of type "TestIssue", to deviate from the default Cucumber setting "Test"
- Revert prefix back to "Test:"
- Add the createTestIssues: false option
- Go over the following page to double check config: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/guides/targetingExistingIssues/

An example of a tagline in one of my feature files where this error pops up is:
  @Test:APP-50197
  Scenario: This is a test scenario

In other cases I have 
  @smoke @Test:APP-50198

```
  Running:  test.feature                                      (4 of 224)
│ Cypress Xray Plugin │ INFO    │ Preprocessing feature file src/e2e/test.feature
│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray...
│ Cypress Xray Plugin │ WARNING │ Mismatch between feature file issue tags and updated Jira issues detected
│ Cypress Xray Plugin │ WARNING │   
│ Cypress Xray Plugin │ WARNING │   Issues contained in feature file tags which were not updated by Jira and might not exist:
│ Cypress Xray Plugin │ WARNING │     APP-50443
│ Cypress Xray Plugin │ WARNING │     APP-50444
│ Cypress Xray Plugin │ WARNING │     APP-50445
│ Cypress Xray Plugin │ WARNING │   Issues updated by Jira which are not present in feature file tags and might have been created:
│ Cypress Xray Plugin │ WARNING │     APP-49892
│ Cypress Xray Plugin │ WARNING │     APP-49893
│ Cypress Xray Plugin │ WARNING │     APP-49894
│ Cypress Xray Plugin │ WARNING │   
│ Cypress Xray Plugin │ WARNING │   Make sure that:
│ Cypress Xray Plugin │ WARNING │   - All issues present in feature file tags belong to existing issues
│ Cypress Xray Plugin │ WARNING │   - Your plugin tag prefix settings are consistent with the ones defined in Xray
│ Cypress Xray Plugin │ WARNING │   
│ Cypress Xray Plugin │ WARNING │   More information:
│ Cypress Xray Plugin │ WARNING │   - https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/guides/targetingExistingIssues/
│ Cypress Xray Plugin │ WARNING │   - https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/cucumber/#prefixes
│ Cypress Xray Plugin │ WARNING │
```

Here are 2 parts of my config I wish to highlight
```

      prefixes: { precondition: 'Precondition:', test: 'Test:' },
      createTestIssues: false,

```

Below is the issue that apparently the plugin cannot find:
![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/70505369/97d46573-0d88-41af-8979-098c7b74efd0)

I am confused as to:
- Why it says the issues cannot be found as they do exist
- It is creating new test issues even though the setting is set to false

### Cypress version

13.6.3

### Plugin version

6.0.0

### Jira/Xray type

Server

### Configuration

```ts
jira: {
      projectKey: 'app',
      url: 'https://jira.app.com',
      attachVideos: false,
      testExecutionIssueSummary: `E2E test execution ${new Date().toISOString()}`,
    },
    xray: {
      uploadScreenshots: true,
      uploadResults: true,
      createTestIssues: false,
    },
    cucumber: {
      featureFileExtension: '.feature',
      prefixes: { precondition: 'Precondition:', test: 'Test:' },
      downloadFeatures: false,
      uploadFeatures: true,
    },
    plugin: {
      normalizeScreenshotNames: true,
    },
```

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hey @keulenIT,

thanks for the bug report. Let me first address one of the things you've tried:

> It is creating new test issues even though the setting is set to false

> createTestIssues: false

This setting does not exist anymore, you do not need to worry about it. It was removed in version [4.0.0](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#400) and should not affect things whatsoever.

---

Your interpretation is correct, the plugin (or rather Xray actually!) is unable to link the uploaded feature file scenarios to Jira issues. This is usually the case when the tags are inconsistent.

Now, as to why Xray is unable to link them: I don't really know, it's weird that it works for most of the tests, but for some it fails.

Can you try the following for e.g. `APP-50443`:
- Export the test issue to a Cucumber feature file and verify that the tags Xray attaches to the scenarios are consistent with the ones in your Cypress feature file ([Xray server](https://docs.getxray.app/pages/viewpage.action?pageId=62268093#Gherkin(BDDTests)-ExporttoCucumber), [Xray cloud](https://docs.getxray.app/display/XRAYCLOUD/Gherkin#Gherkin-ExporttoCucumber))
- Check that you (or the user to which the credentials belong) have permission to actually modify the issues

If none of this helps, you could also try importing the feature file manually (repeatedly), using e.g. `curl` or Postman:

```sh
# Xray server
# Authorization is either:
# - base64-encoded "username:password": "Basic xyz=="
# - PAT-based (https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html): "Bearer ABCDEFG"
curl --location 'https://jira.app.com/rest/raven/latest/import/feature?projectKey=APP' \
--header 'Authorization: Basic abcdef1234567890==' \
--form 'file=@"/path/to/your/feature/file/test.feature"'
```

```sh
# Xray cloud
# Get bearer token...
curl --location 'https://xray.cloud.getxray.app/api/v2/authenticate' \
--header 'Content-Type: application/json' \
--data '{
    "client_id": "<id>",
    "client_secret": "<secret>"
}'
# ...then import using the bearer token
curl --location 'https://xray.cloud.getxray.app/api/v2/import/feature?projectKey=APP' \
--header 'Authorization: Bearer ey...LJFI' \
--form 'file=@"/path/to/your/feature/file/test.feature"'
```

**Comment by keulenIT** [comment]
The good news is; After some trial and error, It seems the issue is not with the plugin. The issue is indeed with the xray uploader as you suspected. In fact, Xray is the one who kept making new issue keys. From what I understand diving into the plugin, it just uploads the cucumber files in json format so it is highly logical that the problem is not tied to the plugin. 

Xray however seems to refuse to upload my issues when the issue link is not the first item in the tag list. There is not something in the documentation about tags having to have a certain order, just that it prioritizes the first issue key if you have multiple issue keys in your tagline. I can consistently reproduce this behavior with the same files while with others it just uploads smoothly, so it is with a high degree of certainty this is the case.

Thank you for your help. I now have a much better understanding of the plugin as well as the jira api.

**Comment by csvtuda** [comment]
> [Xray] prioritizes the first issue key if you have multiple issue keys in your tagline

I assume you mean taglines like `@APP-123 @APP50443`? I hope that this was only possible outside the plugin, since it should detect duplicates.

Thanks for the feedback and for sharing your investigation results. I haven't yet encountered this type of importing behaviour, but will keep it in mind should the issue arise again 👍
