### ISSUE TITLE
Test results are not renewed in Jira

### ISSUE THREAD

**Issue by alexviz7** [Qytera-Gmbh/cypress-xray-plugin#297]
### Description

I configured cypress-xray-plugin in a new project and besides the newer version 6 instead of 4 I haven't changed a thing. 
I configured the Test plan and Test execution ticket in order not to have many auto generated tickets.
In version 4 the tickets were renewed with the new test results. Here on the other hand I see now the test results of only the first Test run. Is that normal? Shouldn't the test results be renewed each time?

### Cypress version

12.17.4

### Plugin version

6.0.0

### Jira/Xray type

Cloud

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by alexviz7** [comment]
Hello, do you have any update to this issue? I want to mention that on CI/CD the plugin is set on true while locally its turned off. When turning back the plugin locally to true then the results show up on jira updated. Therefore I think the issue is on the bamboo configuration or the plugin version. Today I will check with the dev-ops and will update you if we find a solution to this issue by ourselves.

**Comment by csvtuda** [comment]
Hey @alexviz7,

Apologies, I did not really find the time to investigate it properly. The results should obviously always be updated, the test execution should _not_ only show the results of the very first run. Unfortunately, I cannot really reproduce it, as shown here:

https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/9e6d8736-559a-461f-8e03-79e7488ed450

So in my opinion, the bamboo configuration might be worth investigating.

**Comment by alexviz7** [comment]
Hello, after the investigation yesterday we found that the actual node version is not compatible with the newest plugin version. Therefore I downgraded the version to 4.0.3 and it works now. Trivial is though that it worked locally and not on bamboo.

**Comment by csvtuda** [comment]
Thanks for the feedback. I'm assuming the pipeline uploads did not work because the feature files were not at all executed. The `cypress-cucumber-preprocessor` requires [Node >= 18](https://github.com/badeball/cypress-cucumber-preprocessor/blob/5e5580ba40a84303729eaf1128e5b42c0ff1b95b/package.json#L131-L133), which is why the `cypress-xray-plugin` also requires Node >= 18.
