### ISSUE TITLE
JIRA connection failing 

### ISSUE THREAD

**Issue by ChiChaangV** [Qytera-Gmbh/cypress-xray-plugin#306]
### Description

JIRA basic authentication is not working 

used

npx cypress run — env JIRA_USERNAME=“” , JIRA_PASSWORD=“”

### Cypress version

12.17.4

### Plugin version

6.0.0

### Jira/Xray type

Server

### Configuration

```ts
Await configurationXrayPlugin(config,{
  jira: {
    ProjectKey: ‘PPPP’,
    Method: ‘POST’,
    TestExecKey: ‘PPPP-***’,
    URL:’https://***-jira.com/rest/raven/1.0/import/execution/junit’
},
 xray: {
   Upload results: true
}
```

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hey @ChiChaangV,

thanks for the issue. Can you double check that there are _no_ spaces in between your environment variables? Cypress expects a list of [comma separated definitions](https://docs.cypress.io/guides/guides/environment-variables#Option-4---env).

```sh
npx cypress run --env JIRA_USERNAME="" , JIRA_PASSWORD="" # wrong
npx cypress run --env JIRA_USERNAME="",JIRA_PASSWORD=""   # good
```

**Comment by ChiChaangV** [comment]
@csvtuda I did I typo here, I tried with no spaces and that is the error I was getting…I have enabled debug mode and in the logs it see the below log, 

****_GET_https_***_jira.com_rest_raven_1.0_import_execution_junit_rest_api_latest_myself_request.json

**Comment by ChiChaangV** [comment]
@csvtuda i get request failed with status code 400
Make sure you have correctly setup
-JIRA base URL: 
-JIRA authentication:

**Comment by ChiChaangV** [comment]
@csvtuda I think it's JIRA cloud

**Comment by csvtuda** [comment]
In this case, your configuration should look something like this:

```ts
// cypress.config.js
import { addXrayResultUpload, configureXrayPlugin } from "cypress-xray-plugin";

// ...
  async setupNodeEvents(on, config) {
    await configureXrayPlugin(config, {
      jira: {
        projectKey: "PPPP",
        url: "https://xxx.atlassian.com" // replace xxx with your Jira domain
      },
      xray: {
        uploadResults: true
      }
    });
    await addXrayResultUpload(on);
  }
// ...
```

Then, run Cypress using e.g.:

```sh
npx cypress run --env XRAY_CLIENT_ID="ABCDEF",XRAY_CLIENT_SECRET="XYZ",JIRA_USERNAME="xxx@yyy.zzz",JIRA_API_TOKEN="XXXYYY"
```

More information:
- Authentication: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/authentication/
- Example configuration: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/guides/uploadTestResults/#how-it-works

**Comment by ChiChaangV** [comment]
Sorry for the confusion it's JIRA server

**Comment by csvtuda** [comment]
In this case, you could try the following configuration:

```ts
// cypress.config.js
import { addXrayResultUpload, configureXrayPlugin } from "cypress-xray-plugin";

// ...
  async setupNodeEvents(on, config) {
    await configureXrayPlugin(config, {
      jira: {
        projectKey: "PPPP",
        url: "https://-jira.com" // add the missing part
      },
      xray: {
        uploadResults: true
      }
    });
    await addXrayResultUpload(on);
  }
// ...
```

Then run Cypress using:

```sh
npx cypress run --env JIRA_API_TOKEN="XYZ"
```

More information:
- [Token](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/authentication/#pat-authentication)

**Comment by ChiChaangV** [comment]
But it's still not calling the Xray API it's calling the JIRA api,we need raven endpoint for uploading the execution results right

**Comment by csvtuda** [comment]
I don't quite understand the issue, I'm afraid. The plugin will usually use access both Jira's API as well as Xray's API, depending on what it needs to achieve. It knows whether it's in a Jira/Xray server or cloud environment, so it will automatically use the raven endpoint as needed.

For example, for Jira/Xray server:
- POST `${jiraBaseUrl}/rest/raven/latest/import/execution` to upload/create a test execution (Xray API)
- POST `${jiraBaseUrl}/rest/api/2/issue/${issueIdOrKey}/attachments` to upload video attachments (Jira API)

For Jira/Xray cloud, it would instead use the following URLs:
- POST `https://xray.cloud.getxray.app/api/v2/import/execution` to upload/create a test execution (Xray API)
- POST `${jiraBaseUrl}/rest/api/3/issue/${issueIdOrKey}/attachments` to upload video attachments (Jira API)
