### ISSUE TITLE
Test results of grouped test steps

### ISSUE THREAD

**Issue by jerhardt-adesso** [Qytera-Gmbh/cypress-xray-plugin#325]
### Description

Hi,

When grouping multiple it functions under a describe block that contains the test issue key some undesired behavior occurs.

Example:

`
describe('TEST-123', () => {
it('should do A', ...)
it('should do B', ...)
})
`

My expectation is that if one of those steps fails, then the test result that is going to be uploaded to xray ticket TEST-123 is going to be "failed". Somehow the plugin still would upload the result as "success" if the last step was successful although the first one failed. Currently I have implemented a workaround where I keep track of all failed tests in a test run and check the number to not be greater than 0 otherwise throw an error to create a failure towards the end so that the result is being uploaded correctly as "failed". 

Another problem I discovered with my current approach is that screenshots of failed tests are also not being uploaded, because apparently the name does not include the test issue key. Even though the warning message itself clearly shows the test issue key within the file name, it still claims to not be existent. I have even tried to rename the screenshot after it has been taken to follow the warning's proposed naming convention where the key is in the front e.g. "TEST-123  <file-name> - ...", but unfortunately the problems persists.

### Cypress version

13.6.2

### Plugin version

6.0.0

### Jira/Xray type

Server

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by jerhardt-adesso** [comment]
Your first example fits our current approach pretty well:

```
describe('CYP-123', () => {
  it('Click monkey', () => { /* ... */ });
  it('Click tiger', () => { /* ... */ });
  it('Feed elephant', () => { /* ... */ });
});
```

We have been using this approach so far, because we have a lot of different sites and environments where we need to perform the same tests on a regular basis. Grouping all tests that belong to a certain context under a single test in xray seemed more reasonable for us, as it would mean that we don't have to split up every single step into a single test in xray which would increase by the number of sites and environments  that are added and have to be mapped to. We are still experimenting with different ideas, but try to keep everything more modular. 

Another idea of us would be to have a test issue in xray for a given context with multiple test execution tickets that have different environment values set where the results of the cypress tests for each environment are being uploaded to. Unfortunately, I was not able to set the testExecutionIssueKey dynamically while running the tests, so that the results could be uploaded to the same test execution ticket each time, unless I define the variable before I run the tests.

**Comment by csvtuda** [comment]
> Edit: We have changed the structure of our Xray Repository so that it can work with the plugin.

I'm very happy to hear that, because I had been thinking about it and wasn't really able to come up with a clean solution.

The only thing I can now still suggest (and which you're probably already employing) is making use of test environments:
- [Xray documentation](https://docs.getxray.app/display/XRAY/Working+with+Test+Environments)
- [Plugin documentation](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/xray/#testenvironments)
