### ISSUE TITLE
Custom prefix/es not recognised by plugin

### ISSUE THREAD

**Issue by atddkg** [Qytera-Gmbh/cypress-xray-plugin#337]
Hi,

[I am under the impression that I should be able to customise the prefix of scenario tags](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/cucumber/#prefixes) so long as I configure the 'test' prefix in the configuration file and 'Cucumber Export Prefixes', however, this doesn't appear to be the case...

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/169905511/9c444b6e-49b5-45ce-bb38-b784cacfb2a2)

I assume I'm mistaken or is this a bug?

It's just, the 'Cucumber Export Prefixes' page makes me think I can customise the prefixes but the plugin's behaviour seems to strictly require at least the scenario tag to be exactly **TestName:**

For context, if it matters: no Jira issue exists with ID TST-7778 - this is just me using Xray to create it if doesn't exist. I don't think this has any bearing on the problem I'm having.

**Comment by csvtuda** [comment]
Hi @atddkg,

It might be a bug, but for now I cannot really reproduce it:

Project:

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/e3716655-bd60-4052-9cad-6f3e166e9ae1)

Xray configuration (only becomes relevant when the plugin actually uploads the feature file):

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/90f3690b-6055-4084-82f2-4618aeeeb852)

- Are you using the latest version (7.0.0) of the plugin?
- Are there any environment variables defined which might override the prefixes (unlikely, but still)?

**Comment by atddkg** [comment]
> Are you using the latest version (7.0.0) of the plugin?

Yes.

> Are there any environment variables defined which might override the prefixes (unlikely, but still)?

Only the credentials as far as I know (note: following command is run by `execSync()`):

`cypress run --config-file cypress/configurations/qa.config.ts --env JIRA_USERNAME="censored@censored.co.uk",JIRA_API_TOKEN="censored",XRAY_CLIENT_ID="censored",XRAY_CLIENT_SECRET="censored"`

The following configuration works (in terms of Xray receiving the feature files and processing them), but I should note that this doesn't result in test executions getting created (that's my next headache)...

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/169905511/a90e138e-2845-483a-866e-c2161649e5ac)

...and setting the automation framework's scenario tags and config file to look for **TestName:**

Compared to your example project, I'm missing some stuff...

I have no `.cypress-cucumber-preprocessorrc.json` file - docs seem to suggest adding the json-enabled stuff to `package.json`, so I did:

```
	"cypress-cucumber-preprocessor": {
		"filterSpecs": true,
		"omitFiltered": true,
		"json": {
			"enabled": true,
			"output": "cypress/reports/cucumber-report.json"
		}
	}
```

(If you're thinking that the first two properties are causing this issue, I removed them and re-tested, they're not causing this issue).

I have no **global.d.ts** file.

I'm assuming the above files should have been created by installing the plugin?

My package.json

```
{
	"scripts": {
		"data.refresh.open.qa": "tsx cypress/start.ts --refreshTestData --open --environment=qa",
		"open.qa": "tsx cypress/start.ts --open --environment=qa",
		"data.refresh.test.qa": "tsx cypress/start.ts --refreshTestData --test --environment=qa",
		"test.qa": "tsx cypress/start.ts --test --environment=qa",
		"data.refresh.qa": "tsx cypress/start.ts --refreshTestData --environment=qa",
		"data.delete.qa": "tsx cypress/start.ts --deleteTestData --environment=qa",
		"test.tag.example": "tsx cypress/start.ts --test --environment=qa --tags=\"@Smoke\"",
		"lint": "eslint cypress --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
		"lint.fix": "eslint --fix cypress --ext ts,tsx"
	},
	"repository": {
		"type": "git",
		"url": "git+https://github.com/censored/cypress-automation-testing-framework-template.git"
	},
	"devDependencies": {
		"@censored/eslint-config": "github:censored/ESLint#semver:^1.0"
	},
	"dependencies": {
		"@badeball/cypress-cucumber-preprocessor": "^20.0.5",
		"@bahmutov/cypress-esbuild-preprocessor": "^2.2.1",
		"@censored/cypress-initiator": "github:censored/Cypress-Initiator#semver:^1.0.1",
		"@censored/cypress-test-data-utilities": "github:censored/Cypress-Test-Data-Utilities#semver:^1.0.2",
		"@types/node": "^20.12.12",
		"cypress": "^13.10.0",
		"cypress-on-fix": "^1.0.3",
		"cypress-xray-plugin": "^7.0.0",
		"execSync": "^1.0.2",
		"mysql2": "^3.9.7",
		"tsx": "^4.11.0",
		"typescript": "^5.4.5",
		"yargs": "^17.7.2"
	},
	"private": "true",
	"cypress-cucumber-preprocessor": {
		"filterSpecs": true,
		"omitFiltered": true,
		"json": {
			"enabled": true,
			"output": "cypress/reports/cucumber-report.json"
		}
	}
}
```

My config (note: )

```
import { defineConfig } from 'cypress'
import createBundler from '@bahmutov/cypress-esbuild-preprocessor'
import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor'
import { createEsbuildPlugin } from '@badeball/cypress-cucumber-preprocessor/esbuild'
import { configureXrayPlugin, syncFeatureFile } from 'cypress-xray-plugin'
import fix from 'cypress-on-fix'

export const jiraCredentials = 'JIRA_USERNAME="censored@censored.co.uk",JIRA_API_TOKEN="censored"'

export const xrayCredentials = 'XRAY_CLIENT_ID="censored",XRAY_CLIENT_SECRET="censored"'

export default defineConfig({
	e2e: {
		watchForFileChanges: false,
		baseUrl: 'https://www.censored.co.uk/',
		specPattern: 'cypress/tests/**/*.feature',
		viewportWidth: 1440,
		viewportHeight: 1080,
		async setupNodeEvents(
			on: Cypress.PluginEvents,
			config: Cypress.PluginConfigOptions
		): Promise<Cypress.PluginConfigOptions> {
			const fixedOn = fix(on)
			await configureXrayPlugin(
				on,
				config,
				{
					jira: {
						projectKey: 'TST',
						url: 'https://censored.atlassian.net',
						testPlanIssueKey: 'TST-1'
					},
					cucumber: {
						featureFileExtension: '.feature',
						uploadFeatures: true,
						prefixes: {
							test: 'TestId:',
							precondition: 'Precondition:'
						}
					},
					xray: {
						uploadResults: true
					}
				}
			)
			// This is required for the preprocessor to be able to generate JSON reports after each run, and more,
			await addCucumberPreprocessorPlugin(fixedOn, config)
			fixedOn('file:preprocessor', async (file) => {
				await syncFeatureFile(file)
				const cucumberPlugin = createBundler({
					plugins: [createEsbuildPlugin(config)],
				})
				return cucumberPlugin(file)
			})
			on('task', {
				log(message) {
					console.log(message)
					return null
				},
			})
			// Make sure to return the config object as it might have been modified by the plugin.
			return config
		},
	},
})
```

I'm missing `import "dotenv/config";` and `env: process.env,` - do I need these? What do they do?

Hmm, should I instead be comparing to the `request-upload` directory of your example? I'll do so now...

**Comment by atddkg** [comment]
Ah-ha. Delving deeper into the logs, I found this `"response":{"error":"Error importing feature files: issue \"TST-2\" is not a coverable issue."}}` ...will investigate now.

**Comment by atddkg** [comment]
I made my Story (TST-2) coverable in Jira (it now has a `Test Coverage` button) but could still not rely on Xray creating my test tickets.

I randomly thought of changing just the value of the prefix 'Test' back to its original value...

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/169905511/093818fa-a525-4ba4-8157-47aaaa0f487d)

...but leaving the scenarios and config using TestId: to give each test a unique ID.

Hey presto, I have now been able to:

1. Ensure the Test tickets are created/updated
2. Associate the Test tickets to the Story

I am now left with wondering how test executions are supposed to be created, because it's not happening. Hopefully I haven't missed a guide which explains how to make it happen. I thought it would just happen on the assumption that all I need to do is specify the json-enabled stuff in the package.json... I feel like I'm missing a step...

**Comment by csvtuda** [comment]
### Questions

> I'm assuming the above files should have been created by installing the plugin?

No, actually not. The Cypress/Cucumber setup is a little bit complex (I wish it were easier ...). So creating the `.cypress-cucumber-preprocessorrc.json` (in the `package.json` in your case) manually was the way to go here.

> I have no global.d.ts file.

This is not required for successful execution and only included to hide this error in the configuration (the author of the package did not publish any types for it):
![cypress-on-fix import error](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/a573dc45-dd58-4d7e-86e8-3eedbda2e972)

> I'm missing import "dotenv/config"; and env: process.env, - do I need these? What do they do?

They make it easier to define the authentication stuff. Without it, you either:

- need to hardcode the sensitive credentials in the codebase:

    ```ts
    export const jiraCredentials = 'JIRA_USERNAME="censored@censored.co.uk",JIRA_API_TOKEN="censored"'

    export const xrayCredentials = 'XRAY_CLIENT_ID="censored",XRAY_CLIENT_SECRET="censored"'
    ```
- need to run Cypress in complicated CLI commands:

    ```sh
    cypress run --config-file cypress/configurations/qa.config.ts \
      --env JIRA_USERNAME="censored@censored.co.uk",JIRA_API_TOKEN="censored",XRAY_CLIENT_ID="censored",XRAY_CLIENT_SECRET="censored"
    ```

[Dotenv](https://www.npmjs.com/package/dotenv) makes your life easier by moving environment variable definitions into a separate file (usually called `.env`):

```sh
# Xray authentication
XRAY_CLIENT_SECRET="..."
XRAY_CLIENT_ID="..."
# Jira authentication
JIRA_API_TOKEN="..."
JIRA_USERNAME="..."
```

This file can then be added to `.gitignore`. The `import "dotenv/config";` tells Dotenv to parse that file and to add its contents to the `process.env` variable which can then be forwarded to Cypress.

This way, there's:
- no risk of accidentally pushing sensitive credentials to Git
- no need for complicated Cypress invocations anymore: `npx cypress run` and that's it

> Ah-ha. Delving deeper into the logs, I found this "response":{"error":"Error importing feature files: issue \"TST-2\" is not a coverable issue."}}

This is an interesting find, I have never seen this error message! Probably because I had configured that a long time ago and completely forgot about it:
![coverable user story](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/a7b7573b-c8b8-4789-b435-0fbec7b5c53d)

### Upload issue

> I am now left wondering how test executions are supposed to be created, because it's not happening. 

`xray.uploadResults: true` should suffice, even omitting it (it defaults to `true`). The problem must be somewhere else, I assume there's simply no results upload happening at all.

I just double checked the example project, which neither did not upload anything because of a bug. Can you check if the following fixes your problem, too:

```diff
    async setupNodeEvents(on, config) {
      const fixedOn = fix(on);
-     await configureXrayPlugin(on, config, {
+     await configureXrayPlugin(fixedOn, config, {
```

```diff
    async setupNodeEvents(on, config) {
      const fixedOn = fix(on);
+     await addCucumberPreprocessorPlugin(fixedOn, config);
      await configureXrayPlugin(fixedOn, config, {
      ...
      };
-     await addCucumberPreprocessorPlugin(fixedOn, config);
```

Sorry for the confusion, I believe it's all a lot to take in and my clumsiness doesn't really help either.

**Comment by atddkg** [comment]
Thank you for your quick responses and I haven't mentioned how great this plugin is/the time it will save me... if I can make it work lol

From a state of not having generated a report, I believe I made the changes you suggested and get this error.

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/169905511/886704bc-d40e-400e-8d18-763ad7a2237d)

This is after I removed the `output` property from package.json so as not to unduly disturb where the report is deposited/queried from.

By default, it appears that Cypress dumps the report in the root. Quite why the report is being queried from `cypress\configurations\cucumber-report.json` I don't know - that's not where it is.

Logically, you'd think I should specify that the report gets output to `cypress\configurations\`, but the error persists appending the directory I set in the `output` property...

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/169905511/6daab23f-9815-4b9c-b464-90516a53e808)

**Comment by csvtuda** [comment]
> Quite why the report is being queried from cypress\configurations\ I don't know - that's not where it is.

I assume it's because you're passing a path to a config file that is not in the root directory/the default Cypress config location. The issue seems to be that for some reason Cypress changes the working directory of its process to the location of the configuration: https://github.com/cypress-io/cypress/issues/22689

I should be able to solve that issue in the plugin, let me see what I can do.

**Comment by csvtuda** [comment]
I just released version [`7.0.1`](https://www.npmjs.com/package/cypress-xray-plugin/v/7.0.1). Please let me know if the new version is now able to find your Cucumber report.

**Comment by atddkg** [comment]
```
│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber execution: Request failed with status code 400

...

"response":{"error":"There are no valid tests imported"}
```

I'll do some [further reading](https://community.atlassian.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=There+are+no+valid+tests+imported) on this.

Thanks

**Comment by csvtuda** [comment]
Usually, `{"error":"There are no valid tests imported"}` indicates an issue mismatch, e.g. if you've tagged a scenario with `@Test:PRJ-182736`, but there is no issue `PRJ-182736` or it's not a test issue.

That's the only time I've encountered this message in the past.

**Comment by atddkg** [comment]
I haven't looked at those threads yet, effort levels are low because hangover/it's the weekend (looking into this as part of my job).

Just done some experimenting.

The process by which I get results uploading/test execution created (RU/TEC) is:

1. In the automation framework, create new scenarios, tag them, run the tests so Xray/Jira create the test tickets. RU/TEC expected to fail.
2. In the automation framework, change the tags of the scenarios to match the Jira IDs assigned to the automatically created test tickets.
3. Run the tests again for successful RU/TEC.

This loops us back to [#335](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/335)

Because the tags are linking the scenarios to test tickets, I thought that association would persist through the RU/TEC process.

I appreciate your views against it, but now two problems could be solved by your plugin mapping Jira issue IDs of created tickets to the tags -

1. Ensures tag uniqueness, preventing human error leading to ticket overwrites
2. Uploads results/creates test executions first time because the scenarios map to the correct Jira issue IDs

**Comment by atddkg** [comment]
After further experimentation, this step...

> 2. In the automation framework, change the tags of the scenarios to match the Jira issue IDs assigned to the automatically created test tickets.

...seemingly destroys the link between the scenario and Test ticket in terms of when I change the scenario, the Test ticket isn't updated to reflect those changes.

So the state of play is:

I can use my automation framework as the single source of truth to create Test tickets and Test Executions, but updating existing tickets has to be a manual process.

I can live with this.

I'll soldier on trying to implement this workflow somehow using your plugin - [Pure VCS based workflow](https://docs.getxray.app/pages/viewpage.action?pageId=31622264) - step 3 confuses me but I'll figure it out.

Thanks for your help :)
