### ISSUE TITLE
Add custom informations to execution test issue (on summary or description) and assign execution test issue to someone on Jira

### ISSUE THREAD

**Issue by ethoreau** [Qytera-Gmbh/cypress-xray-plugin#359]
Hi,

I would like to know if it is possible to put information from the test executed in the description (or title) of the execution test issue.

For example, executing an order via Cypress and being able to put the order number in the execution test issue created on XRAY.
I've tried several things but it's not conclusive.

I'm using the last version of Cypress and the last version of the plugin.
I looked at the documentation, but maybe I didn't understand all the configuration for jira or xray. I also tried my friend Google, but maybe I don't use the right keywords.

I hope my explanations are clear.

**Comment by ethoreau** [comment]
I forgot to say that I also wanted to know if we could assign the execution test issue to someone in Jira.
Thank you

**Comment by csvtuda** [comment]
Hi @ethoreau,

> I would like to know if it is possible to put information from the test executed in the description (or title) of the execution test issue.

Currently not, but I think it might be a great addition. Do you think providing a function for arbitrary descriptions or summaries would fit your use case?

```ts
await configureXrayPlugin(on, config, {
  jira: {
    url: "https://example.org",
    projectKey: "CYP",
    testExecutionIssueDescription: (testResults: TestResult[]) => `Executed ${testResults.length} tests`,
    testExecutionIssueSummary: (testResults: TestResult[]) => {
      const orders = testResults.filter(result => result.title.includes("order"));
      if (orders) {
        return `Orders: ${orders.join(",")}`;
      }
      return new Date().toLocaleString();
    }
  }
});
```

> I forgot to say that I also wanted to know if we could assign the execution test issue to someone in Jira.

Also not yet possible, but I will implement it as soon as I can.

**Comment by csvtuda** [comment]
Hi @ethoreau,

Regarding the issue assignment: I have just released version [7.2.0](https://www.npmjs.com/package/cypress-xray-plugin/v/7.2.0) ([changelog](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#720)), where you can now [assign issues](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/guides/faq/#assigning-issues). Please let me know if it works or if I need to include more information in the documentation.

> With your proposition, is it possible de add informations to the test execution issue within the test ?

Oh I see, I was on the wrong track there. No, this is currently not possible, but I will try to implement it as soon as I can, there's nothing else in the backlog currently 😀

**Comment by ethoreau** [comment]
Hi @csvtuda 

Thank you for your work ! 

I will check the new version of the plugin and let you know if it all works correctly. Thanks again for this first adding.

> That's not entirely true, the issue is created during results upload. But the issue data such as summary, description etc. are already known beforehand, since they currently need to be hardcoded.

Ok, I see. So after the test is finished, the test execution issue already exists ? Is there a way to get the Xray/Jira issue id ? (for example, get the issue id in the `after` function of Cypress ?)

Currently, I try to use Jira API to create the test execution issue before the run test (this part works, I use `cy.request` to call Jira API) but I can't update the environment variable `JIRA_TEST_EXECUTION_ISSUE_KEY` within the test. Is it possible to do it ? I'm new to Cypress, so maybe I don't do things correctly 😅

**Comment by csvtuda** [comment]
Hi,

> Is it possible to do it ? I'm new to Cypress, so maybe I don't do things correctly 😅

I don't know about environment variables, but in Cypress there are two "environments" so to speak. The browser environment and the Node.js environment. The plugin runs in the Node.js environment. So if you e.g. export an array in your `cypress.config.js` file and fill it from inside a Cypress test, the array will still be empty when the plugin runs in Cypress's `on('after:run')`, which also runs in the Node.js environment.

The only (?) way to transfer data between the two is through `cy.task` calls.

> Ok, I see. So after the test is finished, the test execution issue already exists ?

My plugin calls Xray's [/import/execution/multipart](https://docs.getxray.app/display/XRAY/Import+Execution+Results+-+REST#ImportExecutionResultsREST-XrayJSONresultsMultipart) endpoint with the Cypress test results once all tests are done. Xray then either creates a new test execution issue or updates an existing one. The plugin does not "manually" create test execution issues like you do. This means that the test execution issue does _not_ exist while tests are still running, _unless_ you manually create it beforehand.

> Is there a way to get the Xray/Jira issue id ? (for example, get the issue id in the after function of Cypress ?)

No, you will need to implement this yourself. Off the top of my head, the following approach might work:

1. Manually create a new test execution issue
2. Let Cypress run its tests
    i. From inside the tests, collect test execution issue data to update
3. Let the plugin upload its results
4. Modify the execution issue with your collected data

Something like this (might need some fixing, I did not test it):

```js
// cypress.config.js
import { http} from "node:http";
import { defineConfig } from "cypress";
import { configureXrayPlugin } from "cypress-xray-plugin";
// Allows registering multiple callbacks to Cypress events such as 'after:run'.
// See https://www.npmjs.com/package/cypress-on-fix
import fix from "cypress-on-fix";

export default defineConfig({
  env: process.env,
  e2e: {
    async setupNodeEvents(on, config) {
      const fixedOn = fix(on);
      const executionIssueData: {
        fields: {
          issuetype: {
            name: "Test Execution",
          },
          summary: "My default summary",
          description: "My default description",
        },
      };
      const newExecutionIssueKey = await createExecutionIssue(executionIssueData);
      await configureXrayPlugin(fixedOn, config, {
        jira: {
          // Placeholder values.
          projectKey: "CYP",
          testExecution: {
            key: newExecutionIssueKey 
          },
          url: "https://example.org",
        },
      });
      fixedOn("task", {
        'get-execution-issue': () => newExecutionIssueKey,
        'update-execution-issue': (data) => {
          if (data.summary) {
            executionIssueData.summary = data.summary;
          }
          // ...
        },
      });
      fixedOn("after:run", async () => {
        await modifyIssue(newExecutionIssueKey, executionIssueData);
      });
    },
  },
});

/**
 * Create a new test execution issue.
 * 
 * @params data the execution issue data
 * @returns the execution issue key
 * @see https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-post
 */
async function createExecutionIssue(data) {
  const response = await fetch('https://my.jira.url/rest/api/3/issue', {
    method: 'POST',
    body: JSON.stringify(data),    
    headers: {
      ['Authorization']: '...',
      ['Accept']: 'application/json',
      ['Content-Type']: 'application/json',
    },
  });
  const responseData = await response.json();
  return responseData.key;
}
```

```js
/**
 * Modifies an existing Jira issue.
 * 
 * @params data the issue data
 * @see https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-put
 */
async function modifyIssue(key, data) {
  await fetch(`https://my.jira.url/rest/api/3/issue/${key}`, {
    method: 'PUT',
    body: JSON.stringify(data),    
    headers: {
      ['Authorization']: '...',
      ['Accept']: 'application/json',
      ['Content-Type']: 'application/json',
    },
  });
}
```

Inside a test case:

```js
it('does something', () => {
  cy.task('get-execution-issue')
    .then(key => console.log(`Hooray my issue ${key} is accessible here`));
  // ...
  cy.task('update-execution-issue', { summary: 'My summary from inside a test' })
)};
```

**Comment by ethoreau** [comment]
Hi @csvtuda 

Regarding the new version of the plugin, I tested it and I can assign the test execution issue to someone. 
Huge thank you to you !

And also thank you for your answer regarding updating the description of the test execution issue. I began to work on it, to adjust your code to fit mine. It almost works, the problem is that I don't find anymore the test results in the test execution issue like this : 

<img width="802" alt="Capture d’écran 2024-08-14 à 18 14 50" src="https://github.com/user-attachments/assets/46fb09dc-7cab-4248-8b0c-50cc51e143f2">

I didn't have time to dig to see where the problem was coming from. I'm on vacation for 2 weeks tonight, I will continue testing when I come back in September.

Again thank you for your work and your answers.

**Comment by csvtuda** [comment]
Hey @ethoreau,

> It almost works, the problem is that I don't find anymore the test results in the test execution issue like this

Are you passing the created issue's key to the plugin?

```ts
jira: {
  testExecution: {
    key: newExecutionIssueKey // here
  },
},
```

---

Apart from that, I have released version 7.3.0, which now allows passing a function to the test execution issue data, e.g.:

```ts

// May be updated through tasks.
let finalSummary = 'Default summary';

// ...

jira: {
  testExecution: () => {
    return {
      fields: {
        summary: finalSummary
      }
    };
  }
},
```

The function will be called just before the upload, i.e. _after_ all tests have been run. This basically means that you can simplify the example above and instead use this function.

<details>
<summary>Simplified example</summary>

```js
// cypress.config.js
import { http} from "node:http";
import { defineConfig } from "cypress";
import { configureXrayPlugin } from "cypress-xray-plugin";
// Allows registering multiple callbacks to Cypress events such as 'after:run'.
// See https://www.npmjs.com/package/cypress-on-fix
import fix from "cypress-on-fix";

export default defineConfig({
  env: process.env,
  e2e: {
    async setupNodeEvents(on, config) {
      const fixedOn = fix(on);
      const executionIssueData: {
        fields: {
          issuetype: {
            name: "Test Execution",
          },
          summary: "My default summary",
          description: "My default description",
        },
      };
      const newExecutionIssueKey = await createExecutionIssue(executionIssueData);
      await configureXrayPlugin(fixedOn, config, {
        jira: {
          // Placeholder values.
          projectKey: "CYP",
          testExecution: () => executionIssueData,
          url: "https://example.org",
        },
      });
      fixedOn("task", {
        'get-execution-issue': () => newExecutionIssueKey,
        'update-execution-issue': (data) => {
          if (data.summary) {
            executionIssueData.summary = data.summary;
          }
          // ...
        },
      });
    },
  },
});

/**
 * Create a new test execution issue.
 * 
 * @params data the execution issue data
 * @returns the execution issue key
 * @see https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-post
 */
async function createExecutionIssue(data) {
  const response = await fetch('https://my.jira.url/rest/api/3/issue', {
    method: 'POST',
    body: JSON.stringify(data),    
    headers: {
      ['Authorization']: '...',
      ['Accept']: 'application/json',
      ['Content-Type']: 'application/json',
    },
  });
  const responseData = await response.json();
  return responseData.key;
}
```

Inside a test case:

```js
it('does something', () => {
  // ...
  cy.task('update-execution-issue', { summary: 'My summary from inside a test' })
)};

after(() => {
  cy.task('get-execution-issue')
    .then(key => console.log(`Hooray my issue ${key} is accessible here`));
});
```

</details>

Let me know if this helps you!

**Comment by ethoreau** [comment]
Hey @csvtuda 

I'm back from vacation.

So, I tried again to create a test execution issue and tell your plugin to use this test execution issue to upload tests results.
And it's not working, I don't know what I'm doing wrong.

I'm using the last version of your plugin (and also the last version of Cypress).

I tried to start from the beginning, and when I try this in my `cypress.config.js` file : 
```js
await configureXrayPlugin(on, config, {
    jira: {
        projectKey: "BLABLA",
        url: "https://example.atlassian.net",
        attachVideos: true,
         testExecutionIssueKey: "BLABLA-123"
    },
    plugin: {
        debug: true
     },
     xray: {
         uploadResults: true
      }
});
```

the plugin uploads test results in the existing test execution result (in my example above it's issue BLABLA-123)

But, when I create the test execution issue (which works perfectly) and put the new issue id on the jira config, it's like it's ignore.

I try like this : 
```js
await configureXrayPlugin(on, config, {
    jira: {
        projectKey: "BLABLA",
        url: "https://example.atlassian.net",
        attachVideos: true,
         testExecutionIssueKey: newExecutionIssueKey // created before configueXrayPlugin function
    },
    plugin: {
        debug: true
     },
     xray: {
         uploadResults: true
      }
});
```

and like this : 
```js
await configureXrayPlugin(on, config, {
    jira: {
        projectKey: "BLABLA",
        url: "https://example.atlassian.net",
        attachVideos: true,
        testExecutionIssue: {
            key: newExecutionIssueKey // created before configueXrayPlugin function
         }
    },
    plugin: {
        debug: true
     },
     xray: {
         uploadResults: true
      }
});
```

none of it works.

Concerning the other change you've made, I will try it later (passing a function to the test execution issue data)

**Comment by ethoreau** [comment]
It's me again ! 

I should try the change you've made first 😅 

Passing a function to the test execution issue data actually solved my problem ! (like you say in your comment 😄 )
I managed to add order number in the test execution issue ! 🥳 

So again huge thank you for your work ! 

And I think this issue can be closed 😊

**Comment by csvtuda** [comment]
> But, when I create the test execution issue (which works perfectly) and put the new issue id on the jira config, it's like it's ignore.

The funny thing is that you actually hit a bug with the test execution issue key. It's actually completely ignored by the plugin, I'll have to fix that as soon as possible.

Gladto hear that your workflow is:

- unaffected by this
- now working as desired 🥳
