### ISSUE TITLE
Error 500 when running on bamboo pipeline causing no test results uploaded

### ISSUE THREAD

**Issue by alexviz7** [Qytera-Gmbh/cypress-xray-plugin#366]
### Description

So in the 3rd project ( I have already successfully implemented and configured the cypress xray plugin in two projects running both locally and on the Bamboo pipeline) I tried to configure the newest xray plugin version and it works locally.

However on the pipeline while the build goes green no test results are imported on the tickets. The error in the logs is following:

> build	02-Aug-2024 13:44:10	│ Cypress Xray Plugin │ INFO    │ Importing Cucumber execution...
error	02-Aug-2024 13:44:10	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber execution: Request failed with status code 500
error	02-Aug-2024 13:44:10	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/logs/importExecutionCucumberMultipartError.json
build	02-Aug-2024 13:44:20	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.group.com/jira to respond... (10 seconds)
build	02-Aug-2024 13:44:21	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.group.com/jira to respond... (10 seconds)
build	02-Aug-2024 13:44:21	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.group.com/jira to respond... (10 seconds)
build	02-Aug-2024 13:44:21	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.group.com/jira to respond... (10 seconds)
build	02-Aug-2024 13:44:21	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.group.com/jira to respond... (10 seconds)
build	02-Aug-2024 13:44:22	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.group.com/jira to respond... (10 seconds)
error	02-Aug-2024 13:44:24	│ Cypress Xray Plugin │ ERROR   │ Failed to edit issue: Request failed with status code 429
error	02-Aug-2024 13:44:24	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/logs/editIssue.json
error	02-Aug-2024 13:44:24	│ Cypress Xray Plugin │ ERROR   │ Failed to edit issue: Request failed with status code 429
error	02-Aug-2024 13:44:24	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/logs/editIssue.json
error	02-Aug-2024 13:44:24	│ Cypress Xray Plugin │ ERROR   │ Failed to edit issue: Request failed with status code 429
error	02-Aug-2024 13:44:24	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/logs/editIssue.json
error	02-Aug-2024 13:44:24	│ Cypress Xray Plugin │ ERROR   │ Failed to edit issue: Request failed with status code 429
error	02-Aug-2024 13:44:24	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/logs/editIssue.json
error	02-Aug-2024 13:44:26	│ Cypress Xray Plugin │ ERROR   │ Failed to search issues: Request failed with status code 429
error	02-Aug-2024 13:44:26	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/logs/searchError.json
error	02-Aug-2024 13:44:28	│ Cypress Xray Plugin │ ERROR   │ Failed to edit issue: Request failed with status code 429
error	02-Aug-2024 13:44:28	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/logs/editIssue.json
error	02-Aug-2024 13:44:28	│ Cypress Xray Plugin │ ERROR   │ Failed to edit issue: Request failed with status code 429
error	02-Aug-2024 13:44:28	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/logs/editIssue.json
build	02-Aug-2024 13:44:38	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.group.com/jira to respond... (10 seconds)
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/fscErstellen.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/onlineCryptDetails.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/onlineCryptSeite.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/startSeite.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/vinAnlegen.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/vinMassenbearbeitung.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/vinVerwaltung.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/vinVerwDetails.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/vinVerwaltung.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/vinVerwDetails.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/vinMassenbearbeitung.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/onlineCryptDetails.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/startSeite.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/onlineCryptSeite.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/fscErstellen.generated.feature
build	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/cypress/e2e/feature/generated_features/vinAnlegen.generated.feature
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │ Encountered problems during plugin execution!
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │ PROJ-1469
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │   
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │     Failed to set labels field to value: ["cypress_fsc"]
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │ PROJ-1446
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │   
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │     Failed to set labels field to value: ["cypress_fsc"]
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │ PROJ-1445
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │   
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │     Failed to set labels field to value: ["cypress_fsc"]
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │ PROJ-1442
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │   
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │     Failed to set labels field to value: ["cypress_fsc"]
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │ PROJ-1537
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │   
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │     Failed to set labels field to value: ["cypress_fsc"]
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │ PROJ-1571
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │   
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │     Failed to set labels field to value: ["cypress_fsc"]
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ WARNING │ No test results were uploaded
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber execution results
error	02-Aug-2024 13:44:50	│ Cypress Xray Plugin │ ERROR   │ Failed to search for issues
build	02-Aug-2024 13:44:50	
error	02-Aug-2024 13:44:50	tput: No value for $TERM and no -T specified

So it could be that its the Jira Token not correct. But if its not the case, what could be the causing of the error 500?

### Cypress version

13.13.1

### Plugin version

7.1.0

### Jira/Xray type

Cloud

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hi @alexviz7,

great to hear that this is your third project using the plugin already. It looks like you're encountering more the mentioned problem.

> But if its not the case, what could be the causing of the error 500?

Do you have a way of accessing the actual response? The plugin tells you where it gets written to:

> error 02-Aug-2024 13:44:10 │ Cypress Xray Plugin │ ERROR │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/PROJ-FSCUI-JOB1/proj-ui/logs/importExecutionCucumberMultipartError.json

The information there would help a lot (make sure to scan for sensitive data if you include it in a comment).

> Failed to edit issue: Request failed with status code 429

The Jira API returns 429 Too Many Requests when hitting an [internally defined rate limit](https://developer.atlassian.com/cloud/jira/platform/rate-limiting/#rate-limit-detection). This may also be causing problems, currently the plugin does not retry such failed requests. I will need to fix this as soon as I can.

> Failed to set labels field to value: ["cypress_fsc"]

Does this warning appear locally too? If not, the pipeline credentials might not have the necessary permissions to edit the labels of existing issues. Can you check if that's the case?

**Comment by alexviz7** [comment]
I could not find the json file on the pipeline, but I could reproduce the issue also locally with the add of the Jira execution issue and plan in the command.
![Screenshot 2024-08-06 132007](https://github.com/user-attachments/assets/4809f8fa-b18d-42f1-972a-f113567bd42d)

I rerun the local test command, but without the JIRA_TEST_PLAN_ISSUE_KEY and the fail disapeared and the results were imported on Jira and on the Execution ticket. So there might be a bug on the Test plan?

**Comment by alexviz7** [comment]
The removal of the JIRA_TEST_PLAN_ISSUE_KEY in the pipeline command fixed the issue there too.

**Comment by csvtuda** [comment]
Hi @alexviz7 

I have just released version [7.2.0](https://www.npmjs.com/package/cypress-xray-plugin/v/7.2.0) ([changelog](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#720)). The new version includes a [rate limiting feature](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/guides/faq/#rate-limiting) which should get rid of your 429 Too Many Requests errors.

Regarding the 500 Internal Server error: I have not found the time to investigate this yet, but it will be next on my list.

**Comment by alexviz7** [comment]
The 7.3.0 version plus the addition of:

>     http: {
>       rateLimiting: {
>         requestsPerSecond: 0.95,
>       },
>     },
in the configuration, solved the issue. No error 400 or 500 found in the logs after the implementation. 
Thank you very much.
