### ISSUE TITLE
Error: Failed to upload Cypress test results to Xray execution due to missing 'key' property

### ISSUE THREAD

**Issue by 1911sk** [Qytera-Gmbh/cypress-xray-plugin#383]
### Description

I am trying to upload Cypress test results to a specific Xray execution, but I am encountering the following error message: 

`│ Cypress Xray Plugin │ INFO    │ Importing Cypress execution...
│ Cypress Xray Plugin │ ERROR   │ Failed to import execution: Cannot read properties of undefined (reading 'key')
│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /tmp/ifp/app/test/test/logs/importExecutionMultipartError.json
│ Cypress Xray Plugin │ WARNING │ Encountered problems during plugin execution!
│ Cypress Xray Plugin │ WARNING │ No test results were uploaded
│ Cypress Xray Plugin │ ERROR   │ Failed to import Cypress execution results` 

This issue occurred after a recent update. Before the update, everything worked as expected. I am unsure if the problem lies within the plugin or with Jira itself.

Steps to Reproduce:

1. Set up Cypress with the configuration.
2. Run Cypress tests in a pipeline.
3. The tests execute successfully, but during the upload of the test results to Xray, the following error occurs:
`│ Cypress Xray Plugin │ INFO    │ Importing Cypress execution...
│ Cypress Xray Plugin │ ERROR   │ Failed to import execution: Cannot read properties of undefined (reading 'key')`

Environment:
Cypress Version: 13.14.1
Cypress Xray Plugin Version: 7.2.0
Cypress GitLab Parallel Runner Version: 1.1.3
TypeScript Version: 5.4.5
OS: Sonoma 14.6.1

Error Logs:
`{
  "error": "TypeError: Cannot read properties of undefined (reading 'key')",
  "stacktrace": "TypeError: Cannot read properties of undefined (reading 'key')\n    at ServerClient.onResponse (/node_modules/cypress-xray-plugin/src/client/xray/xray-client-server.js:152:53)\n    at ServerClient.importExecutionMultipart (/node_modules/cypress-xray-plugin/src/client/xray/xray-client.js:102:30)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ImportExecutionCypressCommand.computeResult (/node_modules/cypress-xray-plugin/src/hooks/util/commands/xray/import-execution-cypress-command.js:13:16)\n    at async ImportExecutionCypressCommand.compute (/node_modules/cypress-xray-plugin/src/hooks/command.js:87:16)\n    at async ExecutableGraph.executeFollowedBySuccessors (/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:74:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)"
}`

Additional Context:
This issue appeared after a recent update. Everything worked well before that. I am not sure if this is an issue with the plugin or if it is related to Jira.

Question:
Are there any specific debugging steps I should follow, or is there a known issue with this version of the Cypress Xray plugin that could cause this error?

### Cypress version

13.14.1

### Plugin version

7.2.0

### Jira/Xray type

Cloud

### Configuration

```ts
import { defineConfig } from "cypress";
const getspecFiles = require("cypress-gitlab-parallel-runner");
import { configureXrayPlugin } from "cypress-xray-plugin";
import * as fs from "fs";

export default defineConfig({
  e2e: {
    baseUrl: "https://your-app-url.com",
    async setupNodeEvents(on, config) {
      on("after:spec", (spec, results) => {
        if (results && results.video) {
          const failures = results.tests.some((test) =>
            test.attempts.some((attempt) => attempt.state === "failed")
          );
          if (!failures) {
            fs.unlinkSync(results.video);
          }
        }
      });
      getspecFiles('./cypress/e2e', true);  
      if (process.env.CYPRESS_JIRA_URL) {
        await configureXrayPlugin(on, config, {
          jira: {
            url: process.env.CYPRESS_JIRA_URL,
            projectKey: "PROJECT",
            testExecutionIssueKey: "TEST-123",
            testExecutionIssue: {
              fields: {
                summary: "UI Tests Status",
                description: "Current status of all UI tests."
              }
            }
          },
          xray: {
            uploadScreenshots: true
          }
        });
      }
      return config;
    },
  },
});
```

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hey @1911sk,

thanks for the bug report. Are you using Jira server or Jira cloud? According to the bug description it's cloud, but the error is thrown in the Xray server class, so I'm a little bit confused.

In any case, you can set the plugin to debug mode as follows:

```ts
await configureXrayPlugin(on, config, {
  jira: {
    // ...
  },
  xray: {
    // ...
  },
  plugin: {
    debug: true
  }
});
```

It will then log all requests and responses to a log directory inside the project. Can you check the response logged to a file containing `POST...importExecutionMultipart` in its name? 

If you're actually using Jira/Xray cloud, the response body should [look something like this](https://docs.getxray.app/display/XRAYCLOUD/Import+Execution+Results+-+REST+v2#ImportExecutionResultsRESTv2-XrayJSONresultsMultipart):

```json
{
  "id": "10200",
  "key": "XNP-24",
  "self": "https://www.example.com/rest/api/2/issue/10200"
}
```

For Jira/Xray server, it should [look like this](https://docs.getxray.app/display/XRAY/Import+Execution+Results+-+REST#ImportExecutionResultsREST-XrayJSONresultsMultipart):

```json
{
  "testExecIssue": {
    "id": "10000",
    "key": "DEMO-123",
    "self": "http://www.example.com/jira/rest/api/2/issue/10000"
  }
}
```

The error occurs because the plugin tries to access `testExecIssue.key`, which does not exist in the response body. So something must be off with the response.

**Comment by 1911sk** [comment]
Hi @csvtuda,

Thanks again for the guidance!

We are using Jira Cloud. I’ve enabled the debug mode as suggested and have gathered some logs. Below are the anonymized log files, including the one containing POST...importExecutionMultipart in its name.

**_rest_raven_latest_import_execution_multipart_request.json_**

``` {
  "body": "----------------------------526200988325654192753015\r\nContent-Disposition: form-data; name=\"result\"; filename=\"results.json\"\r\nContent-Type: application/json\r\n\r\n{\"testExecutionKey\":\"XXX-309\",\"tests\":[{\"finish\":\"2024-09-16T08:01:14Z\",\"start\":\"2024-09-16T08:01:09Z\",\"status\":\"PASS\",\"testKey\":\"XXX-286\"},{\"finish\":\"2024-09-16T08:01:19Z\",\"start\":\"2024-09-16T08:01:14Z\",\"status\":\"PASS\",\"testKey\":\"XXX-310\"},{\"finish\":\"2024-09-16T08:01:22Z\",\"start\":\"2024-09-16T08:01:19Z\",\"status\":\"PASS\",\"testKey\":\"XXX-226\"},{\"finish\":\"2024-09-16T08:01:24Z\",\"start\":\"2024-09-16T08:01:22Z\",\"status\":\"PASS\",\"testKey\":\"XXX-213\"},{\"finish\":\"2024-09-16T08:01:26Z\",\"start\":\"2024-09-16T08:01:24Z\",\"status\":\"PASS\",\"testKey\":\"XXX-295\"},{\"finish\":\"2024-09-16T08:01:32Z\",\"start\":\"2024-09-16T08:01:26Z\",\"status\":\"PASS\",\"testKey\":\"XXX-249\"},{\"finish\":\"2024-09-16T08:01:37Z\",\"start\":\"2024-09-16T08:01:32Z\",\"status\":\"PASS\",\"testKey\":\"XXX-237\"},{\"finish\":\"2024-09-16T08:01:48Z\",\"start\":\"2024-09-16T08:01:37Z\",\"status\":\"PASS\",\"testKey\":\"XXX-254\"},{\"finish\":\"2024-09-16T08:01:56Z\",\"start\":\"2024-09-16T08:01:48Z\",\"status\":\"PASS\",\"testKey\":\"XXX-251\"},{\"finish\":\"2024-09-16T08:02:04Z\",\"start\":\"2024-09-16T08:01:56Z\",\"status\":\"PASS\",\"testKey\":\"XXX-271\"},{\"finish\":\"2024-09-16T08:02:12Z\",\"start\":\"2024-09-16T08:02:04Z\",\"status\":\"PASS\",\"testKey\":\"XXX-255\"},{\"finish\":\"2024-09-16T08:02:20Z\",\"start\":\"2024-09-16T08:02:12Z\",\"status\":\"PASS\",\"testKey\":\"XXX-236\"},{\"finish\":\"2024-09-16T08:02:29Z\",\"start\":\"2024-09-16T08:02:20Z\",\"status\":\"PASS\",\"testKey\":\"XXX-241\"},{\"finish\":\"2024-09-16T08:02:36Z\",\"start\":\"2024-09-16T08:02:29Z\",\"status\":\"PASS\",\"testKey\":\"XXX-253\"}]}\r\n----------------------------526200988325654192753015\r\nContent-Disposition: form-data; name=\"info\"; filename=\"info.json\"\r\nContent-Type: application/json\r\n\r\n{\"fields\":{\"description\":\"In this test execution, the current status of all UI tests is displayed.\",\"issuetype\":{\"self\":\"https://example.jaas.service.company.com/rest/api/latest/issuetype/14602\",\"id\":\"14602\",\"description\":\"Represents a Test Execution\",\"iconUrl\":\"https://example.jaas.service.company.com/download/resources/com.xpandit.plugins.xray/images/test-execution.png\",\"name\":\"Test Execution\",\"subtask\":false},\"project\":{\"key\":\"XXX\"},\"summary\":\"Team UI Tests Status\"}}\r\n----------------------------526200988325654192753015--\r\n",
  "headers": {
    "Accept": "application/json, text/plain, */*",
    "Content-Type": "multipart/form-data; boundary=--------------------------526200988325654192753015",
    "Authorization": "Bearer XXX",
    "User-Agent": "axios/1.7.4",
    "Content-Length": "2343",
    "Accept-Encoding": "gzip, compress, deflate, br"
  },
  "url": "https://example.jaas.service.company.com/rest/raven/latest/import/execution/multipart"
}
 ```
**_rest_raven_latest_import_execution_multipart_response.json_**

``` {
  "data": {},
  "headers": {
    "date": "Mon, 16 Sep 2024 08:02:38 GMT",
    "server": "XXX Server",
    "strict-transport-security": "max-age=31556926, max-age=31536000",
    "x-arequestid": "602x7908577x4",
    "referrer-policy": "strict-origin-when-cross-origin",
    "x-xss-protection": "1; mode=block",
    "x-content-type-options": "nosniff",
    "x-frame-options": "SAMEORIGIN",
    "content-security-policy": "sandbox",
    "server-timing": "threadId;desc=168622",
    "x-seraph-loginreason": "OK",
    "x-ratelimit-limit": "-1",
    "x-ratelimit-remaining": "9223372036854775807",
    "x-ratelimit-fillrate": "-1",
    "x-ratelimit-interval-seconds": "1",
    "retry-after": "0",
    "x-asessionid": "XXX",
    "x-ausername": "XXX",
    "cache-control": "no-cache, no-store, no-transform",
    "vary": "User-Agent",
    "content-type": "application/json;charset=UTF-8",
    "set-cookie": "JSESSIONID=XXX; Path=/; Secure; HttpOnly, atlassian.xsrf.token=XXX; Path=/; Secure; SameSite=None",
    "keep-alive": "timeout=5, max=99",
    "connection": "Keep-Alive",
    "transfer-encoding": "chunked"
  },
  "status": 200,
  "statusText": ""
}
 ```
**_importExecutionMultipartError.json_**

``` {
  "error": "TypeError: Cannot read properties of undefined (reading 'key')",
  "stacktrace": "TypeError: Cannot read properties of undefined (reading 'key')\n    at ServerClient.onResponse (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/client/xray/xray-client-server.js:152:53)\n    at ServerClient.importExecutionMultipart (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/client/xray-client.js:102:30)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ImportExecutionCypressCommand.computeResult (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/hooks/util/commands/xray/import-execution-cypress-command.js:13:16)\n    at async ImportExecutionCypressCommand.compute (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/hooks/command.js:87:16)\n    at async ExecutableGraph.executeFollowedBySuccessors (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:74:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 2)\n    at async ExecutableGraph.execute (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:40:9)\n    at async Object.handler (/tmp/project/project-gui-test/node_modules/cypress-xray-plugin/src/plugin.js:116:13)"
}
 ```

Thanks again for your help and patience, it’s greatly appreciated! Let me know if further information is needed.

Best regards!

**Comment by 1911sk** [comment]
Hi @csvtuda,
We received a Jira update last night, and the uploads are working again. It seems the issue was on Jira’s side. The uploads are now being processed successfully. Thank you so much for your help!

**Comment by csvtuda** [comment]
Okay, very weird but I'm glad to hear that everything's back to normal now!
