### ISSUE TITLE
Feature: upload videos

### ISSUE THREAD

**Issue by Zaista** [Qytera-Gmbh/cypress-xray-plugin#40]
Cool plugin, thanks a bunch.
It would be lovely to have an option to upload any videos to the execution issue (as an attachment) in Jira, is that planned?

**Comment by csvtuda** [comment]
Hey @Zaista, thanks for this issue! I honestly always had video capturing disabled, which is why I simply forgot about it entirely. I will look into it in the next few days.

**Comment by csvtuda** [comment]
Hey @Zaista,

I've implemented video attachments in version `3.0.0`. You should be able to upload videos by doing the following things:
1. Address the breaking changes as described here: https://github.com/Qytera-Gmbh/cypress-xray-plugin/releases/tag/v3.0.0
2. Set up Jira authentication as described here: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/authentication/
3. Enable video attachments as described here: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#attachvideo

Feel free to give me a quick feedback once you've tried it out.

**Comment by Zaista** [comment]
Awesome, works like a charm :) Thanks a lot for the quick implementation
