### ISSUE TITLE
Type mismatch issue with configuration

### ISSUE THREAD

**Issue by Zaista** [Qytera-Gmbh/cypress-xray-plugin#41]
There seems to be a mismatch between what documentation says are the optional parameters: https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/xray/#uploadresults

And what's written in the code: https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/src/types/xray/plugin.ts#L47

![image](https://user-images.githubusercontent.com/15846154/236247684-4a3aaa30-737e-43ea-9e92-5d5a3f108d0f.png)

`uploadResults` parameter is mandatory for `xray` configuration.

**Comment by csvtuda** [comment]
Thanks, I will look into it.

**Comment by csvtuda** [comment]
I included the fix in version `2.0.4`. It should be available via `npm`.
