### ISSUE TITLE
Add configuration option for Execution Issue Title / Description

### ISSUE THREAD

**Issue by barnes** [Qytera-Gmbh/cypress-xray-plugin#55]
As we expand our test set, being able to better label the Test Execution issues would be great. Simply being able to set the title as a configuration setting would be great to label the non-prod region, sprint ID, etc to make it easier to identify on the Jira board.

**Comment by csvtuda** [comment]
This is a great suggestion that's long been overdue.

I added support for adding custom summaries in #56 ([documentation](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#testexecutionissuesummary)) and for custom descriptions in #57 ([documentation](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#testexecutionissuedescription)).
Feel free to try it out, the changes are included in [version `3.2.0`](https://www.npmjs.com/package/cypress-xray-plugin).
