### ISSUE TITLE
`filename.replaceAll` is not a function in Bamboo build

### ISSUE THREAD

**Issue by mgomezgg** [Qytera-Gmbh/cypress-xray-plugin#68]
I'm facing with a problem while trying to upload the results to Jira in a Bamboo build created to run e2e tests.

The message shown is the following: 
![githubscreenshot](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/110907622/6bec21a6-4060-45cd-8c1b-ceb313be66fa)

I have a Warning message "filename.replaceAll is not a function" in all the function where I put it the label to link with the Jira ticket.

**Comment by csvtuda** [comment]
Hey @mgomezgg,

do you know which Node version you're running in Bamboo? A quick google search indicates that `replaceAll` for strings was added in NodeJS v15: https://stackoverflow.com/a/66937599

**Comment by mgomezgg** [comment]
Hi @csvtuda,

I'm using the v14.21.3 in Bamboo.
I will try with a newer version and I will let you know 😄 
Thank you!

**Comment by mgomezgg** [comment]
@csvtuda, now is working fine! I'll close the issue.
Thank you!

**Comment by csvtuda** [comment]
Thanks for the quick feedback! I've added the version specifier to the Node.js requirements in the [documentation](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/setup/requirements/#nodejs-v15).
