### ISSUE TITLE
Plugin overwrites existing issue summaries

### ISSUE THREAD

**Issue by alexviz7** [Qytera-Gmbh/cypress-xray-plugin#83]
Hi,

As continuation to the previous [issue](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/79) I realized that some Jira test tickets, that had the prefix 'Test Ui:' would be altered or not be found. Is there a way to put a prefix in the configuration or do I have to delete the 'Test-UI' prefix or write it in the scenario too?
![2023-06-26 12_31_05-cypress config ts -Visual Studio Code  Administrator](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/b1969c5c-3f0f-4311-8f8a-17d9934fcb10)

**Comment by csvtuda** [comment]
Hey,
can you quickly clarify the following points:
1. Are you still running Cucumber feature files or regular Cypress tests?
2. Did the plugin encounter multiple tags/issue keys in the tests targeting these problematic issues?
3. Are you doing data-driven testing, i.e. `Examples` in feature files?

**Comment by alexviz7** [comment]
Hi,  I somehow managed to stop the altering of the Test ticket title so I believe the ticket can be closed.

**Comment by alexviz7** [comment]
To your question:
1. Yes it is a cypress cucumber framework so I work with features.
2. I managed to minimize the issue by putting language tags in the ticket to recognize the scenarios (however I need to investigate this further).  If this wont work out I will have to separate the scenarios in one scenario per ticket to avoid problems.
3. Yes I am using datatables and Examples in many scenarios to avoid repetition.

**Comment by csvtuda** [comment]
> Hi, I somehow managed to stop the altering of the Test ticket title so I believe the ticket can be closed.

Do you still remember what the issue was? This could be helpful for future readers.

**Comment by csvtuda** [comment]
Perfect, thank you. Yes, that option specifies whether the plugin is allowed to overwrite issue summaries when providing their Jira keys. Glad to see it's working 🙌
