### ISSUE TITLE
Prevent backgrounds from becoming precondition issues

### ISSUE THREAD

**Issue by alexviz7** [Qytera-Gmbh/cypress-xray-plugin#86]
In continuation to the previous issues 79, 85 and 84, I have put many test steps in Background
```
  Background: Login
    Given user opens login page
    When user fills username with "login"
    And user fills password with "psw"
    And user clicks on login
    And user checks if language is set to English
```
However now I see a new pre condition ticket created with title Login (test steps were uploaded in this ticket). It should not be considered as a login pre condition test as it always part of the scenarios in the feature, that is the purpose of Background in Features to sum up the common steps.
![2023-06-26 13_12_02-](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/4937bd6b-4111-47e5-b971-6e7dabf73e88)

**Comment by csvtuda** [comment]
I feel like this is out of the plugin's scope. As far as I know, this is simply the way Xray handles imported feature files. Xray provides a detailed description [here](https://docs.getxray.app/display/XRAY/Importing+Cucumber+Tests+-+REST), but I will highlight the relevant parts:

> If the Cucumber feature has a background, a Pre-Condition issue will be created, if the issue key in the tag does [...] exist in JIRA, [it is] updated, containing the information provided in that background.

Regarding Pre-Condition reuse:
> Pre-Conditions:
> - try to find the Pre-Condition by key, if found then update it; else...
> - try to find the Pre-Condition having both:
>   - a label with the original relative path of .feature (e.g. "core/sample_addition.feature)
>   - no other label ending in ".feature"
> - try to find the Pre-Condition having both:
>   - the same Summary
>   - no label ending in ".feature", except the one corresponding to the relative path of the Cucumber file being imported
    create Pre-Condition in that project and add a label with the relative path of the feature

I don't know if there's anything I could do about that, unfortunately.

**Comment by alexviz7** [comment]
Well the problem is since I used this Login Background almost in every Feature I have about 60+ Login Pre-Conditions since its almost never the same precondition. I haven't looked in how the xray configuration is, but from what I read in the link you gave me, the title will be "Background for: Ticket issue" which is more comprehensible as to have 60 times "Login" precondition. 

However I would prefer that the Background steps are added to the scenario of the feature.

**Comment by csvtuda** [comment]
If your background differs from feature file to feature file, I feel like Xray is correctly creating a different precondition for your scenarios/tests. It's also a pretty niche use case, the Gherkin documentation seems to prefer backgrounds like this:

```feature
Background: Login
  Given user opens login page
  # That's it
Scenario: Buy milk
  Given user <user> adds <n> milk bottles to the shopping cart
  When proceed with payment
  Then their balance represents the purchase
```

The plugin can only work with the endpoints Xray's API offers for importing Cucumber tests, which unfortunately is just the one for importing entire files. To update/set *individual steps*:
- the Jira API would need to be used (no big deal)
- the ID of the custom Jira field for Cucumber step would need to be determined (might be difficult)
- a corresponding request would need to be dispatched, e.g. a PUT:
  ```json
  {
    "customfield_12102": "Given x\nWhen y\nThen z\n"
  }
  ```
A hardcoded solution would then also only cover your use case.


I think instead I'm going to add a way for you to modify feature files before running them, so you can move your background steps to the scenario section. Or whatever you would like to do instead in the future.

**Comment by csvtuda** [comment]
Hey @alexviz7,

So I looked into it and found out that the plugin currently already supports your use case. It just requires a little bit of tinkering. The idea is as follows:
1. parse every feature file
2. move any background steps to all scenarios
3. write the files to some directory
4. execute these files instead, including synchronization etc.

### Setup

You will need to install all dependencies necessary for parsing and working with Gherkin:
```sh
npm i -D @cucumber/gherkin
npm i -D @cucumber/messages
npm i -D @cucumber/gherkin-utils
```

### Feature file modification

Here's a function you can add somewhere in your project. The function performs steps 1-3 and returns the path to the generated file:

```ts
import { AstBuilder, GherkinClassicTokenMatcher, Parser } from "@cucumber/gherkin";
import { pretty } from "@cucumber/gherkin-utils";
import { IdGenerator } from "@cucumber/messages";
import fs from "fs";

function mergeBackground(path: string): string {
    if (!path.endsWith(".feature")) {
        return path;
    }

    // See: https://github.com/cucumber/gherkin#library
    const uuidFn = IdGenerator.uuid();
    const builder = new AstBuilder(uuidFn);
    const matcher = new GherkinClassicTokenMatcher();
    const parser = new Parser(builder, matcher);
    const gherkinDocument = parser.parse(fs.readFileSync(path, { encoding: "utf-8" }));

    if (gherkinDocument.feature) {
        // Children can be: background, scenarios, ...
        const children = gherkinDocument.feature.children;
        // Look for a background child first. Remember its steps, then delete it.
        // Afterwards, add its steps to each scenario.
        let backgroundSteps = [];
        // Find background.
        for (let i = 0; i < children.length; i++) {
            const child = children[i];
            if (child.background) {
                for (const step of child.background.steps) {
                    backgroundSteps.push(step);
                }
                // Remove background from feature file entirely.
                gherkinDocument.feature.children = children.filter(
                    (scenario) => scenario !== child
                );
            }
            break;
        }
        // Copy background to scenarios.
        for (const child of gherkinDocument.feature.children) {
            if (child.scenario) {
                child.scenario.steps = [...backgroundSteps, ...child.scenario.steps];
            }
        }
    }

    const filePath = path.replace(".feature", ".generated.feature");
    fs.writeFileSync(filePath, pretty(gherkinDocument, "gherkin"));
    return filePath;
}
```

### cypress.config.ts

All that's left to do is to:
- exclude the generated files from being considered specs themselves to prevent an endless loop:
  ```ts
   specPattern: ["**/*.feature"],
   excludeSpecPattern: ["**/*.generated.feature"],
  ```
- call the extraction function:
  ```ts
  on("file:preprocessor", async (file) => {
      file.filePath = mergeBackground(file.filePath);
      await syncFeatureFile(file);
      const cucumberPlugin = createBundler({
          plugins: [NodeModulesPolyfillPlugin(), createEsbuildPlugin(config)],
      });
      return cucumberPlugin(file);
  });
  ```

You can obviously modify everything as desired (output directory, generated file naming scheme, ...). But for me, this works already. Files like this:

```feature
Feature: Language

  Background: Login
    Given user opens login page
    When user fills username with "user"
    And user fills password with "psw"
    And user clicks on login

  @CYP-2451 @CYP-2546
  Scenario: Change Language to German
    When user checks if language is set to German
    Then the page shows values in "de"
```

are converted into:

```feature
Feature: Language

  @CYP-2451 @CYP-2546
  Scenario: Change Language to German
    Given user opens login page
    When user fills username with "user"
    And user fills password with "psw"
    And user clicks on login
    When user checks if language is set to German
    Then the page shows values in "de"
```

Please let me know what you think.

**Comment by alexviz7** [comment]
First of all thank you very much for your help and the detailed answer you ve send. I tried this out but I still get a Background Login ticket created. 
Test runs with `uploadFeautures: true` and I get when running an error:

```
TypeError: Cannot read properties of undefined (reading 'readFileSync')
    at mergeBackground (C:\Projects\cypress.config.ts:37:28)
    at Object.handler (C:\Projects\cypress.config.ts:109:21)
    at invoke (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:183:18)
...
```

**Comment by csvtuda** [comment]
Did you make sure to add the imports? The `readFileSync` function comes from the following import:

```ts
import fs from "fs";
```

I don't know how you're building your modules, maybe the following will work as well:

```ts
import * as fs from 'fs';
```

**Comment by alexviz7** [comment]
>     * ESM:
>       import * as fs from 'fs';
Thank you this fixed the error `TypeError: Cannot read properties of undefined (reading 'readFileSync')` but the issue is still there.  Again I have Login Preconditions. Furthermore, if I put `uploadFeatures: true` then I have the same issue as in issue [83](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/83) which we closed. The jira ticket title is altered too, although I just wanted to upload the Feature with the background steps together. So either I dont upload anything or my tickets are altered completely (title, tags, cucumber steps and precondition).

**Comment by csvtuda** [comment]
Happy to hear that it somewhat solved your precondition issue!

> However what the solution created is locally a identical clone file with the ending generated.feature filling up my feature folder.

You can change the output path here:
```ts
fs.writeFileSync(filePath, pretty(gherkinDocument, "gherkin"));
//               ^^^^^^^^
```
For example, change it to the following to create them in a single directory which you can then (git)ignore:
```ts
import * as syspath from "path";

function mergeBackground(path: string): string {
  // rest of function ...
  // ...
  const relativePath = path.substring(path.lastIndexOf("cypress"));
  const tmpFilename = syspath.basename(relativePath).replace(".feature", ".generated.feature");
  const tmpDirectory = `tmp/${syspath.dirname(relativePath)}`;
  const tmpFilepath = `${tmpDirectory}/${tmpFilename}`;
  fs.mkdirSync(tmpDirectory, { recursive: true });
  fs.writeFileSync(tmpFilepath, pretty(gherkinDocument, "gherkin"));
  return tmpFilepath;
}
```

You can do whatever you want with the function, basically. It's up to you now! Automatic cleanup would require more work, however (i.e. delete the folder after test execution). I hope a dedicated directory suits your needs as of now.

> A minor issue that is not hindering the test execution is that step is not recognized on vscode.

Interesting, I'm not seeing this problem. I'd like to share my `tsconfig.json`, but it's pretty messed up right now because of development changes. As long as it still works, you should be fine. You could try moving the function to a separate file and importing it afterwards to make your `cypress.config.ts` appear clean again (which it seemingly is).

> So either I dont upload anything or my tickets are altered completely (title, tags, cucumber steps), but I wished only the steps to be uploaded or altered.

Yes, this is the choice you'll have to make (for now).
There's just the one endpoint for importing feature files, and it always imports *everything*, including preconditions, summaries, ...

*But*: Today I've noticed that the endpoint for feature file import accepts an additional `testInfo` JSON file. Although it's not documented what the file may contain, I assume it's the same stuff which can be provided for [the other "import test & test execution" endpoints](https://docs.getxray.app/display/XRAYCLOUD/Using+Xray+JSON+format+to+import+execution+results#UsingXrayJSONformattoimportexecutionresults-%22testInfo%22object-CreatingTestissues).
It would be exactly what's needed to solve all your problems (summary changing etc.).
I will try to play around with it when I find the time (busy week unfortunately).

Fingers crossed 🤞

**Comment by alexviz7** [comment]
Thanks a lot for your help and time, I ll check this solution with filepath. I already have an option to delete files prior execution so I could combine this with the generated features
